### ISSUE TITLE
stable version plan?

### ISSUE THREAD

**Issue by nguyenxndaidev** [lulupointu/vrouter#1]
Thank for publishing vrouter!

Do you have any plan when you will publish a stable version?

**Comment by lulupointu** [comment]
Hi,
Thanks for having a look!

Concerning the stable version, I think I am pretty much dependent on https://github.com/flutter/uxr/wiki/Navigator-2.0-API-Usability-Research

If you don't know, this is a project from the Flutter team to do a usability research on different Navigator 2.0 plug-ins. 
I think this is a unique opportunity to address any blocking issue that many might face and that I might have forgotten.

One the possible issues are addressed I will be pretty confided to release a stable version. This being said, I am already trying to make as little change as possible but I understand if you need something more stable.

Concerning the when, I just submitted an issue on their github (https://github.com/flutter/uxr/issues/12). If they plan to take too much time, I should plan a stable version earlier and I will let you know.

**Comment by nguyenxndaidev** [comment]
Thanks for reply quickly!

The question you made to flutter team is exactly what I am concerning.

I am asking you because I think flutter team might need quite a long time to release next high-level Nav API.

I started to copy angular router with some improvements (mentioned [here](https://github.com/flutter/uxr/issues/6#issuecomment-778750725)) but then I know your plugin, which has some similar features I need. Therefore I am thinking to stop my implementation and try yours while waiting for the official one.

**Comment by lulupointu** [comment]
For the moment (as far as I understand) the Flutter team is not going to release a high-level Nav API. In fact, this is why they are looking into third-parting plug-in to endorse.

Concerning the duration of the study I am waiting for their response before taking any decision.

**Comment by lulupointu** [comment]
They have just answered. Tbh in 2 month I think the package will already be stable but I cannot garantie that I won't break things if it is judged as needed by the usability research.

**Comment by nguyenxndaidev** [comment]
Thanks for your answer!
