### ISSUE TITLE
push navigated but not sync with browser address bar

### ISSUE THREAD

**Issue by johnwangwjq** [lulupointu/vrouter#100]
Me again ;-P

When I call `context.vRouter.push(path);` the page do change to the expected, but the url on the browser address bar didn't-- it stay still the root(ie., "/"). 

I'm sure it's my problem, just don't know where the bug in my code. Could you help give me a little bit guide to locate it? 

Some hints appeared while the bug occure:

- when I pushed, I can see the browser address flash the expected path but change back to the root immediately.
- I got the following errors which doesn't block my interaction with the page(so I used to leave it for later reasoning):
```
════════ Exception caught by scheduler library ═════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
'[]='
Dynamic call of null.
Receiver: "{\"serialCount\":0,\"historyState\":\"{}\"}"
Arguments: ["state", "{\"serialCount\":1,\"historyState\":\"{}\"}"]

When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 721:3   defaultNoSuchMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 61:12                 noSuchMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 716:31  noSuchMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 270:9   _checkAndCall
...
```

**Comment by lulupointu** [comment]
Hi, 

On which version of vrouter are you?
What are the exact step to reproduce to produce this? Launch and push or did you hot restart? did you touch that address bar? Etc

**Comment by johnwangwjq** [comment]
Sorry for the late reply. I've found the reason: Every time I route to a new path, I created a new `MaterialApp` instance. I guess this is wrong. The actual code is like the following:

<details>
  <summary>My newpie code segment</summary>

```
void main() {
  runApp(MultiProvider(
    // Register all the global states
    providers: [
      ChangeNotifierProvider(
        create: (_) => UserSession(
          userSettings: UserSettings(),
          appSettings: AppSettings(),
        ),
      ),
    ],

    /// Configure all the routes
    child: Builder(
      builder: (BuildContext btx) {
        return VRouter(
          debugShowCheckedModeBanner: false,
          initialUrl: navs.loginState.path,
          routes: routes.all.entries
              .map<VRouteElement>((entry) => VWidget(
                    name: entry.key.name,
                    path: entry.key.path,
                    widget: new MaterialApp(MyContentWidget),    //  <==========  my problem
                    buildTransition: (primAnim, secAnim, child) =>
                        FadeTransition(opacity: primAnim, child: child),
                  ))
              .toList(),
          ///// TODO: Uncomment the following to reject anonymous users.
          // beforeEnter: (redirect) async {
          //   if (redirect.to!.startsWith(navs.login.path)) return;
          //   final sess = Provider.of<UserSession>(btx, listen: false);

... ...
```  
</details>

So I guess in a real web application,  MaterialApp should be a singleton. right?

**Comment by lulupointu** [comment]
Glad you could figure it out, here is more explanations if you need: https://vrouter.dev/guide/Essentials/About%20MaterialApp

Feel free to close the issue if your problem is solved 😊

**Comment by lulupointu** [comment]
Also not mentionned in the link: `VRouter` acts as a `MaterialApp` so you should be able to give it your locals directly

**Comment by johnwangwjq** [comment]
WoW!, right on the spot! Using VMaterialApp clear all the errors. 

Thank you so much sir! Where is the "buy me a bear" link?

**Comment by johnwangwjq** [comment]
VRouter is even better !
