### ISSUE TITLE
Is path deleted by vrouter?

### ISSUE THREAD

**Issue by ChristianPauly** [lulupointu/vrouter#101]
Hi there. I have a flutter webapp at https://fluffychat.im/web and I expected that VRouter is doing all routes like this:

https://fluffychat.im/web/#/
https://fluffychat.im/web/#/home
https://fluffychat.im/web/#/login

But instead it is deleting the path and goes to:

https://fluffychat.im/#/
https://fluffychat.im/#/home
https://fluffychat.im/#/login

Which leads to several problems. Files and images cant be loaded and if you click on reloading the page, it redirects you to another page which is under fluffychat.im

Is this a VRouter bug maybe?

**Comment by lulupointu** [comment]
Mmm, yes this might be because of vrouter. I'll check

**Comment by lulupointu** [comment]
Did you try that as well ? 

![image](https://user-images.githubusercontent.com/5128921/122649959-a9108680-d130-11eb-9531-d9cd54e2350f.png)

**Comment by ChristianPauly** [comment]
> Did you try that as well ?
> 
> ![image](https://user-images.githubusercontent.com/5128921/122649959-a9108680-d130-11eb-9531-d9cd54e2350f.png)

Oh thank you very much. I will try. One moment!

**Comment by lulupointu** [comment]
I think what is asked in the picture is needed but not sufficient. The issue being that when VRouter set a url it ignores whatever you might have in the base path. I'm having a look right know to see if I can quickly fix this.

**Comment by ChristianPauly** [comment]
Okay I have updated the index.html of my project and the base tag so far. Unfortenatly it is not yet fixed by this

**Comment by lulupointu** [comment]
And this should still cause an issue when reloading the page doesn't it ?

**Comment by ChristianPauly** [comment]
> And this should still cause an issue when reloading the page doesn't it ?

Correct. It also makes things difficult if I want to get the current domain at runtime. (the webapp is free to be host everywhere)

**Comment by lulupointu** [comment]
They should have been fixed by the commit above. I'm trying to push something else in `v+16` so I'll let you know when you can try. This should be within the hour.

**Comment by lulupointu** [comment]
This should now be fixed. Please use `v1.1.4+16` and let me know how it goes !

**Comment by ChristianPauly** [comment]
Yes it is fixed!! Thank you soooo much :-)
