### ISSUE TITLE
 How do I use Provider "inside" VRouter (Not On Top of VRouter)

### ISSUE THREAD

**Issue by leanhro2812** [lulupointu/vrouter#103]
I used the Provider to get the data from the API and tested it on beforeEnter VGuard to make sure the data was there before I got inside the page
But I don't want to put my whole Provider on top of VRouter, I just want to put it on individual Page_route individually
Because each Page will use its own Provider
How do I use Provider inside VRouter
(Please note that is inside of VRouter , not on top of VRouter )

**Comment by lulupointu** [comment]
Not sure it's the best idea because if you await in `beforeEnter` after clicking somewhere your app might feel janky.

If you really want to do so, the trick is to instantiate you object and use it's reference in `VGuard`, then use `Provider.value` to provide it to provider.

Why do you need the reference and can't you use `context.read` in `VGuard.beforeEnter`? Because `VGuard.beforeEnter` is called *before* the context is created (since you don't know if you want to create the widgets yet). 

What if you still want lazy loading instead of instantiating you object directly? If you are using null-safety, then instead of `final yourVariable = YourVariable()` you should use `late final yourVariable = YourVariable()`. 

Hope think helps!

**Comment by leanhro2812** [comment]
> Not sure it's the best idea because if you await in `beforeEnter` after clicking somewhere your app might feel janky.
> 
> If you really want to do so, the trick is to instantiate you object and use it's reference in `VGuard`, then use `Provider.value` to provide it to provider.
> 
> Why do you need the reference and can't you use `context.read` in `VGuard.beforeEnter`? Because `VGuard.beforeEnter` is called _before_ the context is created (since you don't know if you want to create the widgets yet).
> 
> What if you still want lazy loading instead of instantiating you object directly? If you are using null-safety, then instead of `final yourVariable = YourVariable()` you should use `late final yourVariable = YourVariable()`.
> 
> Hope think helps!

**Comment by leanhro2812** [comment]
> Not sure it's the best idea because if you await in `beforeEnter` after clicking somewhere your app might feel janky.
> 
> If you really want to do so, the trick is to instantiate you object and use it's reference in `VGuard`, then use `Provider.value` to provide it to provider.
> 
> Why do you need the reference and can't you use `context.read` in `VGuard.beforeEnter`? Because `VGuard.beforeEnter` is called _before_ the context is created (since you don't know if you want to create the widgets yet).
> 
> What if you still want lazy loading instead of instantiating you object directly? If you are using null-safety, then instead of `final yourVariable = YourVariable()` you should use `late final yourVariable = YourVariable()`.
> 
> Hope think helps!



> Not sure it's the best idea because if you await in `beforeEnter` after clicking somewhere your app might feel janky.
> 
> If you really want to do so, the trick is to instantiate you object and use it's reference in `VGuard`, then use `Provider.value` to provide it to provider.
> 
> Why do you need the reference and can't you use `context.read` in `VGuard.beforeEnter`? Because `VGuard.beforeEnter` is called _before_ the context is created (since you don't know if you want to create the widgets yet).
> 
> What if you still want lazy loading instead of instantiating you object directly? If you are using null-safety, then instead of `final yourVariable = YourVariable()` you should use `late final yourVariable = YourVariable()`.
> 
> Hope think helps!

Can you help me with a small example?
I can't use Provider inside VRouter
Because VRouter accepts only VRouterElements inside it.
I can't think of any other way

**Comment by leanhro2812** [comment]
I have referenced some of your answers from this article
[https://github.com/lulupointu/vrouter/issues/74](url)
There is some sample code that shows the context being brought from the outside to the inside: class CLASSNAME extends VRouteElementBuilder
So I used that way to be able to use context in beforeEnter

`VRouter(
  // ~ MaterialApp
  routes: [
    VNester(
      path: null,
      widgetBuilder: (child) => createCommonRootTreeWidgets(child),
      // Initializes a few things for the app...
      nestedRoutes: [
        // -----------------------------
        // NON-Protected routes/screens:
        // -----------------------------
        // *ROOT* ('/')
        VRouteRedirector(
          path: Routes.root,
          redirectTo: Routes.login,
        ),
        // *Login Screen*
        VWidget(path: Routes.login, widget: LoginPage()),

        // -------------------------
        // Protected routes/screens:
        // -------------------------
        VUserCompleteGuard(
          context,
          shouldCheckEmailVerified: false,
          stackedRoute:
              VWidget(path: Routes.user_verify_email, widget: UserVerifyEmailPage()),
        ),
        VUserCompleteGuard(
          context,
          shouldCheckProfileComplete: false,
          stackedRoute: VWidget(path: Routes.user_setup, widget: UserSetupPage()),
        ),
        VUserCompleteGuard(
          context,
          stackedRoute: VWidget(path: Routes.home, widget: HomePage()),
        ),
        // ...
        // ...
      ],
    )
  ],
);`

**Comment by lulupointu** [comment]
The issue you referenced was using `Provider` at the top of the app. The is why the `context` was able to locate the provider.

To achieve what *you* what there are 2 things to understand:
1. Provider is just a widget, it can be used in VWidget or VNester
2. Getting the value of a provider in `VGuard.beforeEnter` should not be done with Provider (this is what I explained to you earlier)

### 1. Provider is just a widget, it can be used in VWidget or VNester

If you have a Provider for a screen you could do:
```dart
VWidget(
  path: '/settings',
  widget: Provider(
    create: (_) => Settings(),
    child: SettingsScreen(),
  ),
)
```
Now within `SettingsScreen` you could use `context.watch<Settings>()`

If you want to provide a provider to multiple screens you could use `VNester`:
```dart
VNester(
  path: null,
  widgetBuilder: (child) => Provider(
    create: (_) => UserProfile(),
    child: child,
  ),
  nestedRoutes: [
    // YOUR ROUTES
  ]
)
```
Then is any screen in "YOUR ROUTES" you could use `context.watch<Settings>()`.

### 2. Getting the value of a provider in `VGuard.beforeEnter` should not be done with Provider

**BAD**
```dart
VNester(
  path: null,
  widgetBuilder: (child) => Provider(
    create: (_) => UserProfile(),
    child: child,
  ),
  nestedRoutes: [
    VGuard(
      beforeEnter: (vRedirector) => context.read<UserProfile>().isConnected ? null : vRedirector.push('/login'),
      stackedRoutes: [
        // YOUR ROUTES
      ],
    )
  ],
)
```

**GOOD**
```dart
class MyApp extends StatelessWidget {
  // NOTE that we create an instance of UserProfile here
  // We use "late final" to make it lazy loaded
  late final userProfile = UserProfile();

  @override
  Widget build(BuildContext context) {
    return VRouter(
      routes: [
        // Any route

        // HERE is the interesting part
        VNester(
          path: null,
          widgetBuilder: (child) => Provider.value(
            value: (_) => userProfile, // NOTE how we use the created instance
            child: child,
          ),
          nestedRoutes: [
            VGuard(
              beforeEnter: (vRedirector) =>
                  userProfile.isConnected ? null : vRedirector.push('/login'), // HERE we use the instance and NOT provider
              stackedRoutes: [
                // YOUR ROUTES
              ],
            )
          ],
        ),
      ],
    );
  }
}
```

I'm sure this will help but tell me if you have more doubt :wink:

**Comment by leanhro2812** [comment]
I tried and still can't solve the error
It still gives me the same error as when I got it
Unhandled Exception: Error: Could not find the correct Provider<UserProfile> above this MyApp Widget

**Comment by lulupointu** [comment]
Simply replace `context.read<UserProfile>().getInfo()` with `userProfile.getInfo()` in your example and this should work

**Comment by lulupointu** [comment]
Feel free to close the issue if that worked for you :wink:
