### ISSUE TITLE
How to perform complex navigation in stacked routes?

### ISSUE THREAD

**Issue by satvikreddy** [lulupointu/vrouter#109]
Consider an e-commerce website for this example.

**Routes**:
Each store: '/store/id'
Cart: '/store/id/cart'
Checkout  page: '/store/id/checkout'

**Goal**: I need to pop cart before going to checkout. (So that after checkout we can just pop and land on store instead of cart).

I am having difficulty moving from cart -> checkout using push replacement. (throws error)
I might be using routes incorrectly. Any help is appreciated.

Also, a **second question**, is there a way to pop 2 routes? In case pushReplacement will not work, I can put checkout inside cart and pop twice to land on store post checkout (this is not prefarable but will fix my use case).

Minimal Code below.

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      title: 'Flutter Demo',
      mode: VRouterModes.history,
      routes: [
        VWidget(path: '/', widget: HomePage(), stackedRoutes: [
          VWidget(
              path: '/store/:id',
              widget: Builder(
                builder: (context) => StoreView(
                  id: context.vRouter.pathParameters['id']!,
                ),
              ),
              stackedRoutes: [
                VWidget(
                  path: 'cart',
                  widget: CartView(),
                ),
                VWidget(
                  path: 'checkout',
                  widget: CheckoutView(),
                ),
              ]),
        ]),
      ],
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          TextButton(
            onPressed: () {
              context.vRouter.push("/store/1");
            },
            child: const Text("Store 1"),
          )
        ],
      ),
    );
  }
}

class StoreView extends StatelessWidget {
  final String id;
  StoreView({required this.id});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Text("Store" + id),
        TextButton(
          onPressed: () {
            context.vRouter.push("cart");
          },
          child: const Text("Go to Cart"),
        ),
      ],
    );
  }
}

class CartView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        const Text("CartView"),
        TextButton(
          onPressed: () {
            context.vRouter.pushReplacement("checkout");
          },
          child: const Text("Go to Checkout"),
        ),
      ],
    );
  }
}

class CheckoutView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const Text("CheckoutView");
  }
}

```

**Comment by lulupointu** [comment]
Just use `push` to navigate where you want. Don't think in terms of `pop`.

`push` is actually replacing the entiere stack and animating correctly, so it's easier to use than pop. 

Try it out and tell me if that works. If not I can modify your example to make it work 😉

**Comment by lulupointu** [comment]
`push` NOT starting with `/` is relative so when you are on cart (`/store/id/cart`) and use `push("checkout") ` you actually navigate to `/store/id/cart/checkout` which does not exist. 

What you need in that case is to use absolute navigation instead, like: `push("/store/id/checkout") `

**Comment by lulupointu** [comment]
Btw `push` vs `pushReplacement` is only a different for the web browser history not for the navigation stack, this might be where you got the confusion

**Comment by satvikreddy** [comment]
Thank! that works.
