### ISSUE TITLE
Is there any way to ignore routes? 

### ISSUE THREAD

**Issue by kalismeras61** [lulupointu/vrouter#117]
I have installed flutter web app azure server and also i have installed wordpress in sub folder. When i use this plugin package detects it as url because it is installed in subfolder.

https://www.exampleflutterdomain.com

https://www.exampleflutterdomain.com/wordpress/

with this installations it is trying to open url as a flutter path.

Is there anyway ignoring urls ?

**Comment by lulupointu** [comment]
Hi,

Is that what you are looking for: https://flutter.dev/docs/development/ui/navigation/url-strategies#hosting-a-flutter-app-at-a-non-root-location?

**Comment by lulupointu** [comment]
I'm talking about the last part where you change the `href` in the `index.html`.

In your case you would have `<base href="/wordpress">`

**Comment by kalismeras61** [comment]
@lulupointu yes i understood that. But as i said flutter app installed base folder but wordpress is subfolder. I want to show flutter app as a first.

**Comment by lulupointu** [comment]
I'm sorry but I'm not sure I understood what you are trying to do. I don't understand what is the link between your wordpress app and your flutter app. Could you try explaining differently ?

**Comment by kalismeras61** [comment]
@lulupointu 

Let me explain in a little more detail. Flutter web project and wordpress are kept on the same hosting. Flutter project is in the root folder while worpdress is in the same directory in a separate folder name.

The problem is that when I try to access http://www.domain.com/wordpress/wp-json/ it redirects to the home page of the flutter web page because the vrouter can't find it as a route.

because of this, i think i need to edit below lines.

   VRouteRedirector(
               redirectTo: AppRoutes.home,
               path: r':_(.*)', // .* is a regexp which matching every paths
             )

**Comment by lulupointu** [comment]
Do you want http://www.domain.com/wordpress/wp-json/ to be considered as part of your flutter app or your wordpress ?

**Comment by kalismeras61** [comment]
> Do you want http://www.domain.com/wordpress/wp-json/ to be considered as part of your flutter app or your wordpress ?

Not exactly, I actually use wordpress as a backend. But since Flutter sees it as url path, it can't find this path and redirects immediately. Therefore, I cannot access the wordpress json api.

**Comment by kalismeras61** [comment]
@lulupointu what I actually want is that it does not take all the paths that start with wordpress and continue and do not redirect to flutter home page.

**Comment by lulupointu** [comment]
If you use `toExternal` instead of `to`, and your server is configured properly, I think you should be able to make it work

**Comment by kalismeras61** [comment]
I found another way, thanks.

**Comment by lulupointu** [comment]
Could you share you solution?
