### ISSUE TITLE
Universal Links on iOS

### ISSUE THREAD

**Issue by Lyokone** [lulupointu/vrouter#118]
Hello,

I've been trying to setup the Universal Links for iOS (with the `https://mydomain.com/the/link` scheme and not the custom scheme `customScheme://something`).

Even tho my application is properly opening, I'm redirected to the `initialUrl` page. Installing another package to catch the universal link is properly working but seems less clean.
Can the Navigator 2 and VRouter directly catch the Universal Link or are only deep links with custom scheme are working ?

Thanks a lot.

**Comment by lulupointu** [comment]
Hi,

I don't have personal experience with Universal Links but after some research it looks like this is an issue from the Flutter engine: https://github.com/flutter/flutter/issues/82550

Feel free to follow up there, I thinks once they implement it it will work out of the box with VRouter. If it does not please reopen an issue to let me know!

**Comment by Lyokone** [comment]
Thanks for the answer, I'll track the progress of the issue there.
For anyone wanting to solve this issue directly here a small snippet if it can help someone:
``` dart
import 'package:app_links/app_links.dart';

...

  final _routerKey = GlobalKey<VRouterState>();

  @override
  void initState() {
    if (!kIsWeb) {
      listenToUniversalLinks();
    }
    super.initState();
  }

  listenToUniversalLinks() async {
    if (!Platform.isIOS) {
      return;
    }
    final _appLinks = AppLinks(
      onAppLink: (uri, _) {
        final _url = uri.toString().replaceAll(appDomain, '');
        _routerKey.currentState?.to(_url);
      },
    );

    final uri = await _appLinks.getInitialAppLink();
    if (uri != null) {
      final _url = uri.toString().replaceAll(appDomain, '');
      _routerKey.currentState?.to(_url);
    }
  }

  @override
  Widget build(BuildContext context) {
    return VRouter(
      key: _routerKey,

...
```
