### ISSUE TITLE
Screen re-render when going to a new screen [1.2.0+5]

### ISSUE THREAD

**Issue by leanhro2812** [lulupointu/vrouter#119]
I tried putting print() in the build function of each monitor
And noticed that the current screen re-renders when I go to a new screen.
And right from the new screen, when I go back (backHistory()) it still re-renderre
Even though I check the Dev
tool, the current page is still there

If you pay attention a bit.. The moment you are about to switch to the new screen, the application will be a bit jerky, because right now the old screen is being re-rendered, the feeling will not be smooth.

Flow: 
From HomeScreen => SettingsScreen (HomeScreen will re-render) => SettingsEditScreen (HomeScreen + SettingsScreen will re-render)
From SettingsEditScreen ==(back)==> SettingsScreen (HomeScreen + SettingsScreen will re-render) ==(back)==> HomeScreen (HomeScreen will re-render)

![Screen Shot 2021-07-15 at 7 23 20 PM](https://user-images.githubusercontent.com/45846101/125787372-f764eb69-ada2-45f4-8c55-d8c3155a0d7f.png)

**Comment by lulupointu** [comment]
Widget can be rebuilt (i.e. build fonction can be called) 60 times a seconds in Flutter. This is not supposed to be an issue, if it is you should consider why and find a solution.

[Here is a link](https://stackoverflow.com/a/52249579/5990125) to a SO with more details.

Feel free to close this if I answered your question

**Comment by leanhro2812** [comment]
@lulupointu 
What I mean here is:
When you go to a new page the current page will be re-rendered
I tried at 1 brand new project with 3 screens, And when I go to a new page .
From A => B => C
There are no re-renders appearing

![Screen Shot 2021-07-15 at 7 49 55 PM](https://user-images.githubusercontent.com/45846101/125790839-f26825c7-ec8b-46f0-84ec-bdc3e2ce1f2e.png)

**Comment by lulupointu** [comment]
### 1. Is that a problem?
No. There is a rebuilding (NOT a re-render). Again, the could happen as many time as Flutter wants because this has to be fast.

### 2. Why does this happen with `VRouter`?
It happens because `VRouter` creates local navigation data for each route (the context.vRouter). You think it's only a main root one but there is actually one per screen. Since it rebuilt when the url changes, it must be what causes your widget to rebuilt.
What use a local `VRouterData` rather than a global one? Because when navigating out of a page, the leaving page should have the old information while the new one should have the new information.

### 3. Can it be avoided?
I don't know, maybe. This is not a priority because it should not be an issue but if you want to try and fix it I would welcome the change !

**Comment by leanhro2812** [comment]
I simply want to open a new screen
and the old screen is still there. I just wonder why the old screen is there but it rebuilds
The rebuild only happens when I use a multi-level route
For example:
/settings/edit/1

But when I use (2 independent routes) it doesn't rebuild
/settings
/edit/1

**Comment by lulupointu** [comment]
This is because:
  - When you use independent route, the one you leave is disposed.
  - When you stack routes, the one bellow is still here and might also change, animate, or rebuilt if some data change (like the url)

**Comment by leanhro2812** [comment]
@lulupointu 
When you Use VWidget or VNested in a nested way like this
The previous pages will be rebuilt.
(This is how I used to get the previous page-back effect)
When using this way the effect: "LeftToRight"
But it caused my previous pages to rebuild
```
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return VRouter(
      initialUrl: '/',
      debugShowCheckedModeBanner: false, // VRouter acts as a MaterialApp
      mode: VRouterMode.history, // Remove the '#' from the url
      routes: [
        VWidget(
          path: '/',
          widget: ScreenOne(),
          stackedRoutes: [
            VWidget(
              path: 'two',
              widget: ScreenTwo(),
              stackedRoutes: [
                VWidget(
                  path: 'three',
                  widget: ScreenThree(),
                ),
              ]
            ),
          ]
        ),
      ],
    );
  }
}
```

**Comment by leanhro2812** [comment]
> This is because:
> 
> * When you use independent route, the one you leave is disposed.
> * When you stack routes, the one bellow is still here and might also change, animate, or rebuilt if some data change (like the url)

I will ignore 2 problems:
- I don't use Animation
- I created a new project and it has nothing to do with data

Why is my front page still rebuilding
You can take the example to test, I will provide my 3 screens below with the code above
Here is the full code: 


```
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      initialUrl: '/',
      debugShowCheckedModeBanner: false, // VRouter acts as a MaterialApp
      mode: VRouterMode.history, // Remove the '#' from the url
      routes: [
        VWidget(
          path: '/',
          widget: ScreenOne(),
          stackedRoutes: [
            VWidget(
              path: 'two',
              widget: ScreenTwo(),
              stackedRoutes: [
                VWidget(
                  path: 'three',
                  widget: ScreenThree(),
                ),
              ]
            ),
          ]
        ),
      ],
    );
  }
}

class ScreenOne extends StatefulWidget {
  @override
  _ScreenOneState createState() => _ScreenOneState();
}

class _ScreenOneState extends State<ScreenOne> {
  @override
  Widget build(BuildContext context) {
    print('Screen One');
    return Scaffold(
      appBar: AppBar(
        title: Text('Screen One'),
        leading: IconButton(
          icon: Icon(Icons.arrow_back, color: Colors.black),
          onPressed: () {
            context.vRouter.historyBack();
          },
        ),
      ),
      body: Column(
        children: [
          Text('Screen One')
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          context.vRouter.to('/two');
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class ScreenTwo extends StatefulWidget {
  @override
  _ScreenTwoState createState() => _ScreenTwoState();
}

class _ScreenTwoState extends State<ScreenTwo> {
  @override
  Widget build(BuildContext context) {
    print('Screen Two');
    return Scaffold(
      appBar: AppBar(
        title: Text('Screen Two'),
        leading: IconButton(
          icon: Icon(Icons.arrow_back, color: Colors.black),
          onPressed: () {
            context.vRouter.historyBack();
          },
        ),
      ),
      body: Column(
        children: [
          Text('Screen Two')
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          context.vRouter.to('/two/three');

        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class ScreenThree extends StatefulWidget {
  @override
  _ScreenThreeState createState() => _ScreenThreeState();
}

class _ScreenThreeState extends State<ScreenThree> {
  @override
  Widget build(BuildContext context) {
    print('Screen Three');
    return Scaffold(
      appBar: AppBar(
        title: Text('Screen Three'),
        leading: IconButton(
          icon: Icon(Icons.arrow_back, color: Colors.black),
          onPressed: () {
            context.vRouter.historyBack();
          },
        ),
      ),
      body: Column(
        children: [
          Text('Screen Three')
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.pop(context);
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by leanhro2812** [comment]
@lulupointu 
When the page rebuilds it makes the page feel jerky. If you use the simple demo code I provide you will not feel it clearly. But when put into practice, rebuilding a page will make you see the application very clearly

**Comment by leanhro2812** [comment]
I wish VWidget could create a transition like the default Nav does

Open a new page => Right TO Left
Back to previous page (back) => Left TO Right
That's what I expected.

But here's the difference:
First :
  - When I use nested routes. It helps me do : LeftToRight when I leave . But it caused my front page to rebuild

Monday:
- I use standalone routes so my previous pages don't get rebuilt when going to a new site. But when I left it was RightToLeft instead of what I expected was LeftToRight

**Comment by lulupointu** [comment]
As discussed, using `stackedRoutes` was the right choice for you. 

I'm sorry that you `build` function is called because of VRouter but for the 3rd time, you should not care. If you do there is an issue with your app and I urge you to read this [SO answer entirely to understand why](https://stackoverflow.com/questions/52249578/how-to-deal-with-unwanted-widget-build/52249579#52249579).

**Comment by Varunml3** [comment]
Calling the build function doesn't result in a re-render when the exact same widget tree is returned. The slow part of the process is rendering so the jerkiness can only be attributed to the rendering of the transition animation or the incumbent widget tree, not calling the build method more than once.
