### ISSUE TITLE
Can I just change the url without switching routes?

### ISSUE THREAD

**Issue by YeungKC** [lulupointu/vrouter#120]
I have a form page where I want the url to change with the form content (so that users can copy the url to share it), but still keep it on the page without using isReplacement to call to.

**Comment by lulupointu** [comment]
I think if you use queryParameters and `to(context.vRouter.url, isReplacement: true, queryParameters:...) ` this should work

**Comment by YeungKC** [comment]
In fact the parameters I need to change are not queryParameters but pathParameters, and I want to not need to reload the current page, I just need to manage it by state and update the url.

**Comment by YeungKC** [comment]
btw, I now go through window.history.replaceState to solve it.

**Comment by lulupointu** [comment]
You have to give your different VWidgets the same ValueKey. 

replaceState should not cause any issue even if it's not very elegant ^^

**Comment by YeungKC** [comment]
the key！！！thanks
