### ISSUE TITLE
Create an 'opaque' route using VPage?

### ISSUE THREAD

**Issue by tksuns12** [lulupointu/vrouter#124]
I'm trying to make some glassmorphismic page. I need to make the ```PageRoute``` transparent when I navigate. However, with vrouter, it seems that the only way to access to the ```PageRoute``` is ```VPage``` but ```opaque``` property is not exposed in there so it's impossible to make the upcoming page transparent.

Could you expose that property in ```VPage``` class or anywhere that is accessible?

**Comment by lulupointu** [comment]
Saying that you need `VPage` is right. As you mentioned, you must change the `PageRoute`. Since `PageRoute` is created by a `Page` and the default page (used in `VWidget`, which is `MaterialPage` or `CupertinoPage`) is opaque, you need to create your own `Page` and give it to `VPage`.

<details>
<summary>
Here is a small example
</summary>

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      routes: [
        VWidget(
          path: null,
          widget: Center(
            child: Text("I'm bellow!"),
          ),
          stackedRoutes: [
            VPage(
              path: '/',
              pageBuilder: (key, child, name) => OpaquePage(
                child: child,
                key: key,
                name: name,
              ),
              widget: Opacity(
                opacity: 0.5,
                child: Container(color: Colors.blueAccent),
              ),
            )
          ],
        )
      ],
    );
  }
}

class OpaquePage extends Page {
  final Widget child;
  final LocalKey key;
  final String? name;

  OpaquePage({required this.child, required this.key, required this.name});

  @override
  Route createRoute(BuildContext context) {
    return PageRouteBuilder(
      settings: this,
      opaque: false, // Here you can set opaque
      pageBuilder: (_, __, ___) => child,
    );
  }
}
```
</details>

**Comment by tksuns12** [comment]
Yes this is exactly the solution I was looking for. Much respect to your capability! Thank you very much.
