### ISSUE TITLE
An alternative to onWillPop?

### ISSUE THREAD

**Issue by Mussab00** [lulupointu/vrouter#138]
Is there and alternative to:
` return WillPopScope(`
         `onWillPop: () async {`
         ` return false;`
         `},`
`child: Container()...}`
to 'deactivate'/ingnore back button press?

**Comment by lulupointu** [comment]
Check this out: https://vrouter.dev/guide/Advanced/Pop%20Events/onSystemPop :wink:

**Comment by Mussab00** [comment]
![image](https://user-images.githubusercontent.com/32457409/132239282-a13c4f1a-97a3-4cd0-9cae-287de25b9466.png)
It doesn't seem to register the back press :)

**Comment by lulupointu** [comment]
Oh yes if you use it in a `showDialog` there might be an issue. 

`WillPopScope` does not work ?

**Comment by Mussab00** [comment]
WillPopScope worked before i started using vRouter

**Comment by lulupointu** [comment]
I just looked into the code of `WillPopScope` and this makes, it's more for Nav1 I suppose.

I will look into `VWidgetGuard` and come back to you.

**Comment by Mussab00** [comment]
Alright, thanks for the quick answers :D

**Comment by lulupointu** [comment]
Solved in `v+12`

I'm afraid `VWidgetGuard.onPop` does not work but I can't find why and I have too much works at the moment. I hope this part of the fix will be enough for you. In any case removing onPop in quite easy with a `GestureHandler` so I could give you a quick fix if needed.

Let me know how that goes and feel free to close the issue if that's solved!
