### ISSUE TITLE
Nesting a constant widget

### ISSUE THREAD

**Issue by blambe** [lulupointu/vrouter#139]
Hi,

I am trying to nest in a constant widget, specifically a ProviderScope from riverpod, based on url.

Essentially, when the url is '/thisSection/:id/thisAction' I am trying to insert a ProviderScope with an override to load the data from ':id' into a provider, to be used by 'thisAction'. This is easily done with VNester, however if switching to '/thisSection/:id/thisOtherAction', the vNester is rebuilt causing repeat calls to load the data from ':id'.  Even using keys to make animation transitions work appropriately, the widget is still rebuilt.

Is there a way to get a non-rebuilding widget nested in? The other thought I've had is to use a single widget that makes changes according to a Query Parameter in the url instead, though I've have to attempt this to see if it works.

I guess the question specifically is, is there a way to use url to effect a build in only the single top most widget on the screen, without effecting a rebuild of the entire tree it belongs to.

Sorry if this doesn't make sense I can try to clarify further.

**Comment by lulupointu** [comment]
If you mean that you are trying to prevent a Widget instantiation OR a Widget.build (or State.build) method, then you can't. It's wanted and does not matter.

What *is* possible however (if indeed the tree is well formed), it to prevent the reconstruction of a `State`. This is why your call for loading the data should be placed in a `State`. Check this SO answer for more info: https://stackoverflow.com/a/52249579/5990125

Btw between `'/thisSection/:id/thisAction` and `/thisSection/:id/thisOtherAction` the id *may* have changed (if the user manually typed a url). So you should add a check in `didUpdateDependencies` and load the thing from the new id if needed.

**Comment by blambe** [comment]
I think the answer is no as you've stated. I'm using riverpod for state management and there are certainly many ways to skin the cat as they say.

What I had in mind was using the url for a targeted change within a widget, similar to an SPA where '#section' jumps you to the appropriate 'section' of an already loaded webpage. In my case, I was shooting to make a page where '/:id/' loaded the actual full screen widget, then the next part 'thisAction' or 'thisOtherAction' served only to modify a widget within the '/:id/' screen.

I can do this easily with query parameters instead of path parameters, but then could I push a change in query parameter to the url without actually reloading the full ':id' page, again similar to how an SPA would perform?

Not a breaking issue, its working fine for me with the initial setup already, but may be handy for future cases and/or optimization.

**Comment by lulupointu** [comment]
But this **is** already possible, look at https://vrouter.dev/guide/Essentials/Getting%20Started/VRouter

If you use the sidebar to click on `VRouter`, `VRouteElement` or `VRouter Magic` you will see that the end of the url changes (exactly like you want), but the screen scroll smoothly without being rebuilt. It that what you are looking for?

**Comment by blambe** [comment]
Yes an effect like that is what I'm looking for, is that in the documentation elsewhere?

Also I apologize, I was actually looking back through my debugging and realized a mistake I had made. I was printing on rebuild of my widget so I thought that is was also re-initializing my provider as well, but adding a print to the provider itself shows that although the widget is rebuilt, the provider is only called on the initial instance, so re-loading of data does not seem to be an issue in this case.

Thanks again for the quick help!

**Comment by lulupointu** [comment]
There is no documentation on this precise subject. There source code of the website is public though: https://github.com/lulupointu/vrouter_website. In [this](https://github.com/lulupointu/vrouter_website/blob/master/lib/routes/guide_routes.dart) file you can see the routes implementation and how I use the keys (which are the most important)

It seems that you are getting there if initState is not called again ! Do tell me if you need more help

**Comment by blambe** [comment]
Thanks for pointing me in the right direction, great job on all of this!
