### ISSUE TITLE
onPop and onSystemPop - VRedirector vs. BuildContext Issue

### ISSUE THREAD

**Issue by orenagiv** [lulupointu/vrouter#14]
Hi @lulupointu,

In the documentation about onPop and onSystemPop it's indicated that the context is passed and can be used with the VRouterData.of(context).push(...
https://vrouter.dev/guide/Advanced/Pop%20Events

However, it seems the onPop/onSystemPop functions return Function(VRedirector) and not Function(BuildContext).

Am I missing something?

**Comment by lulupointu** [comment]
Oh yes the context is the old version. I changed this to vRedirector, as in beforeLeave and beforeEnter. Please refer to those in the meantime to see how this work. But I need to redo this documentation for this anyway because I added this feature recently.
