### ISSUE TITLE
context.vRouter.toNamed doesnt work

### ISSUE THREAD

**Issue by Lasslos** [lulupointu/vrouter#142]
Hey Guys,

I have a problem with `context.vRouter.toNamed`. I have a flutter web application. 

Basically, what happens is that i tap on my `sideMenuItemWidget`, which calls `context.vRouter.toNamed`. Even though I have both the routes itself and also a fallback 404 route defined, it throws an error, that no matching route could be found. I don't understand that. 

<details>
<summary>
Error:
</summary>

>╞═══════════════════════════════════════════════════════════════════ EXCEPTION CAUGHT BY GESTURE ══╡
The following NotFoundErrorNameResult was thrown while handling a gesture:
Could not find the VRouteElement named /last_post.
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/vrouter/src/core/vrouter_delegate.dart 261:7                         [_getUrlFromName]
packages/vrouter/src/core/vrouter_delegate.dart 1419:13                       toNamed
packages/vrouter/src/core/vrouter_delegate.dart 2082:13                       toNamed
packages/vrouter/src/core/local_vrouter_data.dart 184:26                      toNamed
packages/website/widgets/side_menu_item_widget.dart 24:16                     <fn>
packages/flutter/src/material/ink_well.dart 989:21                            [_handleTap]
packages/flutter/src/gestures/recognizer.dart 193:24                          invokeCallback
packages/flutter/src/gestures/tap.dart 608:48                                 handleTapUp
packages/flutter/src/gestures/tap.dart 296:5                                  [_checkUp]
packages/flutter/src/gestures/tap.dart 230:7                                  handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 558:9                           handleEvent
packages/flutter/src/gestures/pointer_router.dart 94:12                       [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 139:9                       <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13      forEach
packages/flutter/src/gestures/pointer_router.dart 137:17                      [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 123:7                       route
packages/flutter/src/gestures/binding.dart 440:19                             handleEvent
packages/flutter/src/gestures/binding.dart 420:14                             dispatchEvent
packages/flutter/src/rendering/binding.dart 278:11                            dispatchEvent
packages/flutter/src/gestures/binding.dart 374:7                              [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 338:5                              handlePointerEvent
packages/flutter/src/gestures/binding.dart 296:7                              [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 279:32                             [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1018:13                           invoke1
lib/_engine/engine/platform_dispatcher.dart 182:5                             invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 130:39                                [_onPointerData]
lib/_engine/engine/pointer_binding.dart 555:18                                <fn>
lib/_engine/engine/pointer_binding.dart 508:21                                <fn>
lib/_engine/engine/pointer_binding.dart 216:16                                loggedHandler
Handler: "onTap"
Recognizer:
  TapGestureRecognizer#d116b
════════════════════════════════════════════════════════════════════════════════════════════════════
</details>

The (in my opinion) important code:

<details>
<summary>
main.dart
</summary>

```dart
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => VRouter(
        debugShowCheckedModeBanner: false,
        title: 'Canada - Laslo Hauschild',
        theme: _buildTheme(Brightness.light),
        darkTheme: _buildTheme(Brightness.dark),
        themeMode: ThemeMode.system,
        routes: myRoutes,
      );
````
</details>

<details>
<summary>
my_routes.dart
</summary>

```dart
final List<VRouteElement> myRoutes = [
  VNester(
    path: '/',
    widgetBuilder: (Widget child) => PageLayout(child: child),
    nestedRoutes: [
      VRouteRedirector(path: '', redirectTo: '/overview'),
      VWidget(path: 'overview', widget: const OverviewPage()),
      VWidget(path: 'last_post', widget: const LastPost()),
      VWidget(path: 'all_posts', widget: const AllPostsPage()),
    ],
  ),
  VWidget(path: '/login', widget: const LoginPage()),
  VWidget(path: '*', widget: const NotFoundPage())
];`
side_menu_item_widget.dart
`@override
  Widget build(BuildContext context) {
    return InkWell(
      onHover: (bool hovering) {
        hoverRoute.value = hovering ? sideMenuItem : null;
      },
      onTap: () {
        activeRoute.value = sideMenuItem;
        context.vRouter.toNamed(sideMenuItem.path);
      },
```
</details>

<details>
<summary>
side_menu_items.dart:
</summary>

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

const SideMenuItem overviewRoute = SideMenuItem(
    'Überblick', '/overview', Icons.view_compact_outlined, Icons.view_compact);
const SideMenuItem lastPostRoute = SideMenuItem('Letzter Post',
    '/last_post', Icons.landscape_outlined, Icons.landscape);
const SideMenuItem allPostsRoute = SideMenuItem(
    'Alle Posts', '/all_posts', Icons.view_array_outlined, Icons.view_array);
const SideMenuItem loginRoute =
    SideMenuItem('Login', '/login', Icons.login_outlined, Icons.login);

final List<SideMenuItem> sideMenuItems = [
  overviewRoute,
  lastPostRoute,
  allPostsRoute,
  loginRoute
];

Rx<SideMenuItem?> hoverRoute = Rx<SideMenuItem?>(null);
Rx<SideMenuItem?> activeRoute = Rx<SideMenuItem?>(sideMenuItems.first);

class SideMenuItem {
  final String name;
  final String path;
  final IconData iconActive;
  final IconData iconInactive;

  const SideMenuItem(this.name, this.path, this.iconInactive, this.iconActive);

  Widget stateBuilder(Widget Function(bool isHovered, bool isActive) builder) =>
      Obx(() => builder(hoverRoute.value == this, activeRoute.value == this));
}
```

</details>

The full repository: https://github.com/Lasslos/website

**Comment by lulupointu** [comment]
Hi!

`toNamed` takes advantage of the `name` argument of the `VRouteElement`s. For example:

```dart
// If you have this VRouteElement
VWidget(path: 'something', widget: SomeWidget(), name: 'deep')

// You can navigate using
context.vRouter.toNamed('deep');
```

However you don't **need** this to navigate, you simply have to use `to` instead of `toNamed`:

```dart
VWidget(path: '/login', widget: LoginScreen())

// Then
context.vRouter.to('/login');
```

Don't hesitate to read the documentation, either from:
  - [pub.dev](https://pub.dev/packages/vrouter)
  - [vrouter.dev](https://vrouter.dev/)
  - The comments in the code source itself

PS: I edited your question so that you can see how to format on Github. All in all there where plenty of information and the problem was clearly stated. The only bothering part was the formatting. You can try to edit your question to see how I did the formatting.

**Comment by Lasslos** [comment]
Thanks!
