### ISSUE TITLE
Nested and Stacked routes

### ISSUE THREAD

**Issue by carmas123** [lulupointu/vrouter#143]
I am happy to use your library, I think it's really very powerful, but I've a big problem to know how the nesting routes work with stack.

I've a dashboard with a nesting routes that work very well when I move from page to other using `VNester.builder`.

Now my problem is that I need to open a new page over the nested scaffold.

I try to add a `stackedRoutes` into the `VNester` but it's doesn't work because the new page is pushed into the nested scaffold.

This is my structure

- Home
- List
- - Detail
        [ Nested1, Nested2, Nested3, ...]
    
Now when I'm into the Nested3 (for example) I need to push a new page over the Detail Stack and then I've added my VWidget into the `stackedRoutes` of Detail tree but the url is not recognized.

```
Liststatic final routes = [
  VWidget(
    path: login,
    widget: LoginPage(),
  ),
  VGuard(
    beforeEnter: (vRedirector) async => !isLoggedIn ? vRedirector.to(login) : null,
    stackedRoutes: guardedRoutes,
  ),

  // NOT FOUND
  VRouteRedirector(
    redirectTo: login,
    path: r'*',
  ),
];

static final guardedRoutes = [
  VWidget(
    path: "home",
    widget: HomePage(),
    stackedRoutes: homeChildren,
  ),
];

static final homeChildren = [
  VWidget.builder(
    path: "list",
    builder: (BuildContext context, VRouterData state) {
      return ListPage(),
      );
    },
    stackedRoutes: listChildren,
  ),
];

static final listChildren = [
  VNester.builder(
    path: "detail/:id",
    widgetBuilder: (BuildContext context, VRouterData state, Widget child) {
      return DetailPage(child);
    },
    nestedRoutes: [
      /// NESTED 1
      VWidget.builder(
        path: null,
        builder: (BuildContext context, VRouterData state) => const Nested1View(),
      ),

      /// NESTED 2
      VWidget.builder(
        path: 'page2',
        builder: (BuildContext context, VRouterData state) => const Nested2View(),
      ),

      /// NESTED 3
      VWidget.builder(
        path: 'page3',
        builder: (BuildContext context, VRouterData state) => const Nested3View(),
      ),
    ],
    stackedRoutes: detailChildren,
  ),
];

static final detailChildren = [
  VWidget.builder(
    path: 'page3/:id',
    builder: (BuildContext context, VRouterData state) {
      return Page3SubDetail();
    },
  ),
];

```

Now:
When I push "/home" all work.
Then when I push "/list" all work
Then when I push "/list/detail/1" all work
Then when I push "/list/detail/1/page2" all work
Then when I push "/list/detail/1/page3" all work

Then when I push "/list/detail/1/page3/123"  NOT WORK

The "/list/detail/1/page3/123" must be opened over the stack has a new page but it's is not recognized and go to not found page.

**Comment by lulupointu** [comment]
I see your problem, this is one of the "issue" with `VNester`: It has to know the inner route to display over the top one. In your case I guess you want to show `Nested3View` bellow `Page3SubDetail` but `VRouter` has no way of knowing this unless you tell it. 

The easiest way is the following:

```dart
VWidget.builder(
  path: 'page3*', // Use "*" to match any url starting with "page3", which includes "page3/:id"
  builder: (BuildContext context, VRouterData state) => const Nested3View(),
),
```

Another more restrictive (which is often better but might be harder to scale depending on your usecase) is to use aliases:

```dart
VWidget.builder(
  path: 'page3',
  aliases: ['page3/:id'], // Also match "page3/:id"
  builder: (BuildContext context, VRouterData state) => const Nested3View(),
),
```

Hope this helps, have fun 😊

**Comment by carmas123** [comment]
I close this issue because I solved with you help and by adding 

```
    VPopHandler(
      onPop: (vRedirector) async => vRedirector.historyBack(),
      stackedRoutes: [
...
      ]
    )
```

over the stacked subdetail pages.

My best regards man
