### ISSUE TITLE
Not getting Query parameters from deep link

### ISSUE THREAD

**Issue by hannahlutd** [lulupointu/vrouter#147]
I have a deeplink opening my app. The app opens, it goes to the correct screen, but the query parameters are coming back empty. 

`context.vRouter.path` is returning the path, but `context.vRouter.pathParameters` returns `{}`

The query is called "user" so I also tried `context.vRouter.pathParameters['user']` and that returns null.

**Comment by lulupointu** [comment]
**path** parameters are not the same as **query** parameters.

**Path parameters**: are the parameters in the url path that you define. For example if your path is `/user/:id` and the current url is `/user/2` then the path parameters are `{id: 2}`.

**Query parameters**: are the parameters in the url after the `?`. For example if the current url is `/user?user=2` then the query parameters are `{user: 2}`.

With that newly gained knowledge, let me know if you see any issue and where ! 😊
