### ISSUE TITLE
[Question] - Known the current named route

### ISSUE THREAD

**Issue by carmas123** [lulupointu/vrouter#148]
Hi, I',ve a VRouter filled with some children and all of these have a "name" property setted.
Now there is a way to know what of these is the current?

Into the VRouter.of(context) there is not property "name" but only path.

**Comment by carmas123** [comment]
Yes but how I can know the value. My problem is that into the Scaffold I need to know if the current path is a specific name.

To know the current path I use `VRouter.of(context).path` and it's for example return "/path/of/my/page", now if I have a VWidget named "test_name", there is a way to know if the current url is "test_name"

**Comment by lulupointu** [comment]
I don't understand why `VRouter.of(context).names` does not answer your question. Could you try to explain a bit more maybe?
