### ISSUE TITLE
Data driven declarative vrouter possible

### ISSUE THREAD

**Issue by gedw99** [lulupointu/vrouter#15]
I read that the intent is for eventually the router to be declaritive.

I want to know if you mean data driven at runtime or code generator based ?

I am using adaptive cards for data driven content and so looking to hook it up with a data driven router 

Thankyou again for this project

**Comment by lulupointu** [comment]
One thing I can guarantee is that this package is not likely to be based on code generation. Auto_route does that well and I am not found of the approach.

As you can see in #13, I might bring some significant changes by enabling nested VRouter.
If this is the case, it should enable for some kind of declarative routing.

**Comment by gedw99** [comment]
> One thing I can guarantee is that this package is not likely to be based on code generation. Auto_route does that well and I am not found of the approach.
> 
> As you can see in #13, I might bring some significant changes by enabling nested VRouter.
> If this is the case, it should enable for some kind of declarative routing.

Yep i see what you mean with the github example.

What i mean by declarative is where YAL drives the router. For example:
https://www.katacoda.com/envoyproxy/scenarios/file-based-dynamic-routing-configuration
- envoy-compleed.yaml
- envoy1-completed.yaml shows nesting of the yaml routers.

**Comment by lulupointu** [comment]
I'm not familiar with this but I think the only way to support this kind of configuration (for vrouter or any other package) would be to build a parser. In any case this does not feel ideal.

**Comment by gedw99** [comment]
yeah its too complicated for vrouter. just an example of the concept.
