### ISSUE TITLE
[Bug] No MaterialLocalizations found when passing in custom key.

### ISSUE THREAD

**Issue by masseelch** [lulupointu/vrouter#152]
Hey @lulupointu, when passing in a key like described in #7, I get `No MaterialLocalizations found.`

Am I doing something wrong or is this buggish?

**Comment by lulupointu** [comment]
I've never seen an issue with this and lots of test use the `key` so I'm surprise this does not work. Are you creating the `GlobalKey` inside a **Stateful**Widget?

**Comment by lulupointu** [comment]
The `VRouter` widget itself is **above** the `Material` widget it creates. The `navigatorKey` would indeed work. Otherwise you can manually place a `Material` widget above `VRouter`, this would not cause any issue.

**Comment by masseelch** [comment]
> The `VRouter` widget itself is **above** the `Material` widget it creates. The `navigatorKey` would indeed work. Otherwise you can manually place a `Material` widget above `VRouter`, this would not cause any issue.

I added a `GlobalKey<NavigatorState>` and use that instead. Feels "more right" to me. Thanks!
