### ISSUE TITLE
Internationalization - AppLocalizations.of(context) null using VMaterialApp

### ISSUE THREAD

**Issue by dominikseger** [lulupointu/vrouter#156]
Hello,

I followed the documentation for implementing internationalization https://flutter.dev/docs/development/accessibility-and-localization/internationalization. While doing so I found out that AppLocalizations.of(context) returns null when using VMaterialApp. Is this a known issue, or is there a workaround?

**Comment by lulupointu** [comment]
I realize that `VMaterialApp` is badly named and badly documented so that's my bad as well
