### ISSUE TITLE
BlocBuilder & modalMottomSheet

### ISSUE THREAD

**Issue by pMertDogan** [lulupointu/vrouter#165]
Hi,

My current vRouterDef is like this.
```

VRouter(
        debugShowCheckedModeBanner: false,
        key: _routerKey,
        initialUrl: '/home',
        navigatorObservers: [
          BotToastNavigatorObserver(),
        ],
        routes: [
          VWidget(path: '/landing', widget: LandingPage()),
          VWidget(
              path: '/loading',
              // widget: Loading()),
              widget: Builder(
                builder: (context) => Loading(
                  isItLoginRegister:
                      context.vRouter.pathParameters['isItLoginRegister'] ==
                          'true',
                ),
              )),
          VWidget(
            path: '/error',
            // widget:  Loading(),
            widget: Builder(
              builder: (context) => Scaffold(
                body: Center(
                  child: Text(
                      context.vRouter.pathParameters['error'] ?? 'error :/'),
                ),
              ),
            ),
          ),
          VGuard(stackedRoutes: [
            VWidget(
                path: '/home',
                widget: BlocProvider<UserBloc>.value(
                  value: UserBloc(context.read<AuthBloc>()),
                  child: HomeScreen(),
                )),
            // VWidget(path: '/home', widget: Builder(builder: (context) => HomeScreen(showLinkSuccesUI : context.vRouter
            //     .pathParameters['showLinkSuccesUI'] ==
            //     'true',),))
            VRouteRedirector(path: ':_(.+)', redirectTo: '/home')
          ])
        ])
```

I want to use BlocUser inside /home widgets. Page is working correctly but unable to use BlocUser on modalBottomSheet cause I just implement the BlocProvider<UserBloc> inside the VWidget and VWidget is inside VRouter. As we know Vrouter has own navigator class , any modalbottomsheet can use BlocUser cause when we navigated to modalBottmSheet its just navigate to other router and this router do not have any BlocProvider<UserBloc>.

I can fix this if I was wrap Vrouter with BlocProvider<UserBloc> but this means UserBloc will be global bloc.I don't want it.

![resim](https://user-images.githubusercontent.com/23584565/140426988-10e5413a-03c4-4181-a4f2-f724d9ff0b69.png)

If we look the widget tree we can see that there is two child for VRouter. Its has 2 navigation, one is homescreen and the other one is bottosheet. I tried blocprovider.value but cant fix it.

![resim](https://user-images.githubusercontent.com/23584565/140427252-26f35d0f-6d7b-4a75-9248-3af1c6ad1db7.png)

Any idea?

**Comment by lulupointu** [comment]
I understand your issue, this is quite common but fortunately easy to solve. You simple have to pass a reference to your `UserBloc` to `showFriendsSheet` and use `BlocProvider.value` at the top of `showModalBottomSheet.builder`.

Here is a small example:
```dart
Future<dynamic> showFriendsSheet(BuildContext context, UserBloc userBloc) {
  return showModalBottomSheet(
    context: context,
    builder: (context) {
      return BlocProvider.value(
        value: userBloc,
        child: BlocBuilder(
          builder: (context, state) {
            return state.maybeWhen(...);
          },
        ),
      );
    },
  );
}
```

To use it, grab the reference to `UserBloc` inside `/home` as you normally would:

```dart
onPressed: () => showFriendsSheet(context, BlocProvider.of<UserBloc>(context))
```

Btw, this has nothing to do with your issue but you should NOT use the `BlocProvider<UserBloc>.value` constructor inside `VWidget('/home)` since you are creating the bloc. Use the `BlocProvider<UserBloc>` constructor instead.

**Comment by pMertDogan** [comment]
Thanks , that's fixed my problem.
