### ISSUE TITLE
Refresh the sample app cause a 404 in release mode

### ISSUE THREAD

**Issue by daichehadeo** [lulupointu/vrouter#167]
Hello,

I found an issue while reloading the sample application. When you are in hot reload in the `/bob/profile` path for instance and hit refresh on your web browser it works perfectly.
However if you do a: 
```
flutter build web
```

and then inside the web folder you expose your application locally using for instance python3:
```
python3 -m http.server
```
You go to the /bob/profile and you refresh the page you got a 404 not found:
```
Error response
Error code: 404

Message: File not found.

Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.
```
I have the same issue on my project. Do you know how to fix this ? Maybe I missed something ?

Thanks for your help!

**Comment by lulupointu** [comment]
Are you using `VRouterMode.history` ? If so have you read the documentation on it? Which basically points towards this well-made vue router documentation of the subject: https://router.vuejs.org/guide/essentials/history-mode.html

**Comment by daichehadeo** [comment]
OK I understood the issue. Thanks for your answer!
