### ISSUE TITLE
VWidgetGuard behavior in flutter web

### ISSUE THREAD

**Issue by satvikreddy** [lulupointu/vrouter#172]
Does VWidgetGaurd work in flutter web? Clicking android back button (or) browser back button seems to pop without calling the VWidgetGaurd's beforeLeave.

What I want to achieve is when on base route (1st route) and user clicks android back, show a dialog to close the app instead of directly poping the web page on browser.

How can this be achieved?

Thanks.

**Comment by lulupointu** [comment]
I don't understand, are you developping for web or mobile? There is no "android back button" apart from within android apps. Am I missing something ?

**Comment by satvikreddy** [comment]
I meant the browser back button when using flutter web in mobile browser.

The android system back button can be used to go to previous route in android when using browser.

**Comment by ojm-it** [comment]
@satvikreddy Is this related to your problem? 

https://vrouter.dev/guide/Advanced/Navigation%20Control/Web%20Caveat

> When a user tries to access an external url by clicking on a button where you use context.vRouter.toExternal, everything works as expected.
>
> When a user tries to access an external url either by typing it, or using the forward/backward button to navigate to an external url, you can’t prevent the user from navigating. This means that trying to use vRedirector.stopRedirection, vRedirector.to, ... in beforeLeave will be ignored. 
>
> Reloading the page cannot be stopped as well.
>
> Everything else should work as expected.

**Comment by satvikreddy** [comment]
Yes, this is. Thanks.
