### ISSUE TITLE
Error in example when routing fastly between pages  

### ISSUE THREAD

**Issue by ViliusP** [lulupointu/vrouter#178]
Tested on Oneplus 7

Steps to reproduce:

1. Debug [example](https://github.com/lulupointu/vrouter/tree/main/example);
2. Sign in;
3. Quickly route between pages by tapping on bottom navigation bar buttons;
4. It should throw "A GlobalKey was used multiple times inside one widget's child list.' error;

Video: 

https://user-images.githubusercontent.com/35105611/150971007-d3899074-6431-4530-b3ac-c60be5ce7e5d.mp4

<details>
<summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on Ubuntu 20.04.3 LTS 5.4.0-96-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
```

</details>

**Comment by lulupointu** [comment]
Yes, this is a known issue when you add slow animations + fast switching. The error does not appear in production though since its just an assert. 

Here is an issue answering this in more details: https://github.com/lulupointu/vrouter/issues/77
