### ISSUE TITLE
remove the # from url.

### ISSUE THREAD

**Issue by Loa212** [lulupointu/vrouter#18]
Hello !

Wonderful package. I was wondering if there is an easy way to remove the # from the url.

Like
                                        .
https://flutter-web-app/#/login

to --> https://flutter-web-app/login

Thanks to whoever responds

**Comment by lulupointu** [comment]
Hi, yes it's very easy, just use the the `mode` parameter:

```dart
VRouter(mode: VRouterMode.history, routes: ...)
```

Check [https://vrouter.dev/guide/Essentials/HTML5%20History%20Mode](https://vrouter.dev/guide/Essentials/HTML5%20History%20Mode), there are links to instruction to what you must do to make it work on a server.
