### ISSUE TITLE
Weird animation in nested pages

### ISSUE THREAD

**Issue by benjaminschreck** [lulupointu/vrouter#182]
When I navigate through nested pages there is a weird Animation where I see the buttons of the Page before. 
Is this a known issue? If yes how can I solve it? 

https://user-images.githubusercontent.com/64160104/154098008-a80b1583-1c44-43ca-bd55-54a23fc44268.mov

**Comment by lulupointu** [comment]
Wow, I've never seen that before. Do you have a reproducible example?

**Comment by benjaminschreck** [comment]
https://github.com/benjaminschreck/vrouter_problem

I uploaded a reproducible example.

**Comment by benjaminschreck** [comment]
The solution was to wrap every VWidget with a Scaffold

**Comment by benjaminschreck** [comment]
The solution was to wrap every widget in the VWidget with a Scaffold
```dart
VWidget(
    path: "/home",
    widget: Scaffold(body: HomeView()),
)
```
