### ISSUE TITLE
[Feature request] allow to remove the # from the start of the url

### ISSUE THREAD

**Issue by Shakedkod** [lulupointu/vrouter#196]
if you use the VRouter package and try to use something like url_strategy to remove the # in the start of the url, it don't do that and sometimes I find that it doesn't let you to move between pages by changing the url:

![Capture2](https://user-images.githubusercontent.com/82947988/177029539-d904ec16-58e5-4bf4-a942-d6683b07042c.PNG)
![Capture3](https://user-images.githubusercontent.com/82947988/177029543-388af5c7-81e6-4c37-964f-e3a242b92276.PNG)

**Comment by lulupointu** [comment]
This is already a feature: https://vrouter.dev/guide/Essentials/HTML5%20History%20Mode 😉
