### ISSUE TITLE
Pop not going back to previous screen

### ISSUE THREAD

**Issue by BenQoder** [lulupointu/vrouter#20]
VRouterData.of(context).pop() doesn't return to previous state

**Comment by lulupointu** [comment]
No it does not.
See https://vrouter.dev/guide/Advanced/Pop%20Events if you want to understand how pop works.

If you want, the previous url is stored in VRouter.previousUrl. I don't yet support going back in the web history but this can be achieve using the [js package](https://pub.dev/packages/js) and window.history.back(). This will only work on the web of course.

**Comment by BenQoder** [comment]
Going back to history does not work on the Mobile app either.

If I push a screen from home route like VRouterData.of(context).push("/profile") for instance, its not possible to return back the home page with VRouterData.of(context).pop()?

Must I push VRouterData.of(context).push("/home") to go back the home screen again?

**Comment by lulupointu** [comment]
Yes, or use `VRouter.of(context).push(VRouter.of(context).previousUrl))`

**Comment by lulupointu** [comment]
Also, since `pop` pops the deepest `VStack`, you can also use this structure:

```dart
VRouter(
  routes: [
    VStacked(
      path: '/home',
      widget: HomeScreen(),
      subroutes: [
        VStacked(
          path: '/profile',
          widget: ProfileScreen(),
        ),
      ],
    ),
  ],
)
```

In which can poping from `'/profile'` will indeed get you back to `'/home'`.
It really depends on you use case !

**Comment by BenQoder** [comment]
Let me use this example

```dart
VRouter(
  routes: [
    VStacked(
      path: '/home',
      widget: HomeScreen(),
      subroutes: [
        VStacked(
          path: '/profile',
          widget: ProfileScreen(),
        ),
        VStacked(
          path: '/settings',
          widget: SettingsScreen(),
        ),
      ],
    ),
  ],
)
```


If I am on the /profile screen then navigate to /settings screen.
How can I use
```dart
VRouterData.of(context).pop()
```
to navigate back to the /profile screen from /settings and have the state of /profile persevered.

**Comment by lulupointu** [comment]
You can't.

I think what you want is this:

```dart
VRouter(
  routes: [
    VStacked(
      path: '/home',
      widget: HomeScreen(),
      subroutes: [
        VStacked(
          path: '/profile',
          widget: ProfileScreen(),
          subroutes: [
              VStacked(
                path: '/settings',
                widget: SettingsScreen(),
              ),
           ],
        ),
      ],
    ),
  ],
)
```

`VStacked` stacks itself on top of the previous `VRouteElement` of the route.
So using the code above, if you are at `'/settings'` the route is: `VStacked('home') -> VStacked('/profile') -> VStacked('/settings')`
So `settings` is stacked on top of `profile` which is stacked on `home`.

You see how this work? The staking logic is not the same as navigator 2.0, once you are used to it, this is even more powerful :1st_place_medal:

**Comment by BenQoder** [comment]
I understand the nested approach here.
That means some Screens must be placed in multiple locations for the stack to work well. 
Correct?

Take for instance

```dart
VRouter(
  routes: [
    VStacked(
      path: '/home',
      widget: HomeScreen(),
      subroutes: [
        VStacked(
          path: '/post/:id',
          widget: DisplayPostScreen(),
        ),
        VStacked(
          path: '/profile',
          widget: ProfileScreen(),
          subroutes: [
              VStacked(
                path: '/post/:id',
                widget: DisplayPostScreen(),
                subroutes: [
                   VStacked(
                     path: '/post/:id',
                     widget: DisplayPostScreen(),
                 )
               ]
              ),
              VStacked(
                path: '/settings',
                widget: SettingsScreen(),
              ),
           ],
        ),
      ],
    ),
  ],
)
```

1. I want to be able to view a post by ```.push("post/1")``` from the Home Screen
2. If post created by user is displayed on the ```ProfileScreen()```, I want to view it by ```.push("post/1")```
3. If I have a Similar Post section, a ```PostScreenScreen()``` stack will have to be nested within ```PostScreenScreen()``` Stack.

**Comment by lulupointu** [comment]
I am not sure I understand what you want. 

What I can tell you is that you should not have routes with the same path. 
Also having path argument with the same identifier is also bad practice, especially in the same route.
To prevent this you might want to use relative paths (path not starting with '/') and rename your path arguments. So for example if I take what you did and create relative path:

```dart
VRouter(
  routes: [
    VStacked(
      path: '/home',
      widget: HomeScreen(),
      subroutes: [
        VStacked(
          path: 'post/:homePostId',
          widget: DisplayPostScreen(),
        ),
        VStacked(
          path: '/profile',
          widget: ProfileScreen(),
          subroutes: [
              VStacked(
                path: 'post/:profilePostId',
                widget: DisplayPostScreen(),
                subroutes: [
                   VStacked(
                     path: 'post/:otherPostId',
                     widget: DisplayPostScreen(),
                 )
               ]
              ),
              VStacked(
                path: '/settings',
                widget: SettingsScreen(),
              ),
           ],
        ),
      ],
    ),
  ],
)
```

With that, your 3 scenario are accessed by different paths:
Case 1: `.push('/home/post/1')`
Case 2: `.push('/profile/post/1')`
Case 3: `.push('/profile/post/1/post/2')`

**Comment by lulupointu** [comment]
I understand why you would want the same path arguments. The will work but a better practice which still does what you want (i.e. having access to the id from DisplayPostScreen, independently from where it is, you could use the following:

```dart
VRouter(
  routes: [
    VStacked(
      path: '/home',
      widget: HomeScreen(),
      subroutes: [
        VStacked(
          path: 'post/:homePostId',
          widget: Builder(builder: (context) => DisplayPostScreen(id: VRouter.of(context).pathParameters['homePostId'])),
        ),
        VStacked(
          path: '/profile',
          widget: ProfileScreen(),
          subroutes: [
              VStacked(
                path: 'post/:profilePostId',
                widget: Builder(builder: (context) => DisplayPostScreen(id: VRouter.of(context).pathParameters['profilePostId'])),
                subroutes: [
                   VStacked(
                     path: 'post/:otherPostId',
                     widget: Builder(builder: (context) => DisplayPostScreen(id: VRouter.of(context).pathParameters['otherPostId'])),
                 )
               ]
              ),
              VStacked(
                path: '/settings',
                widget: SettingsScreen(),
              ),
           ],
        ),
      ],
    ),
  ],
)
```

Where `DisplayPostScreen` takes id as a named argument. Note that id is a string here but you can easily convert this to an int of course.

**Comment by BenQoder** [comment]
Thank you for your time @lulupointu.

Coming from React Navigation (React Native), I believe it works by overlaying stacks on top each other.
When ```.push()``` is called, it renders the new stack above the rest and when ```.pop()`` it dismisses it.
This way they will be no need for deeply nested stacks.
With this current approach, it will be hard to navigate deeply without loosing state or jumping to another stack.

Following your idea the stack structure will look like this, and it becomes even more harder if the different post screens should be visited deeply while changing id.
 
```
--AppRouter
---- GuestStack
------ WelcomeScreen
-------- LoginScreen

---- AuthenticatedStack
------ HomeScreen
-------- PostScreen **
---------- PostScreen **
-------- ProfileScreen
---------- PostScreen **
------------ PostScreen **
-------------- PostScreen **
-------- SettingsScreen
```

But following React Navigation Stack Pattern, we can have a single post screen on the entire stack and avoid too much nesting.

```
--AppRouter
---- GuestStack
------ WelcomeScreen
------ LoginScreen

---- AuthenticatedStack
------ HomeScreen
------ PostScreen **
------ ProfilesScreen
------ SettingsScreen
```

This way, when you are on the HomeScreen and then ```.push()``` the PostScreen, It doesn't dismiss the HomeScreen, It Overlays Over It And No State Will Be Lost, and when you ```.pop()```, it simply dismisses the topmost overlay.

I hope you understand me.
I believe this cannot be achieved by this package at the moment but it must be really nice to avoid too much nesting where possible.

👌🏾👌🏾👌🏾👌🏾👌🏾👌🏾

**Comment by lulupointu** [comment]
I do understand what you are trying to achieve and you are right, I don't think vrouter is the best fit for that.

You are searching for something like React Navigation while my package is closer to React router.
