### ISSUE TITLE
colored logs are not working on iOS

### ISSUE THREAD

**Issue by krille-chan** [lulupointu/vrouter#200]
When debugging an app on iOS using a macbook, the colored logs are not working. It looks kinda broken:

```
flutter: \^[[32m[VRouter: INFO] Successfully navigated to "/home" using VRouter.to <…>
```
Maybe an option to disable the logs or even better a platform check in the package to not color the logs on iOS would be nice.

**Comment by lulupointu** [comment]
Or you using Xcode? On Vscode/Android Studio it should work independently of the platform.

You can always disable logs using:
```dart
VRouter(
  logs: VLogs.none,
  ...,
)
```

**Comment by lulupointu** [comment]
Closing because I need more information. Feel free to reopen if you have.
