### ISSUE TITLE
Push hash to history

### ISSUE THREAD

**Issue by CosmicPangolin** [lulupointu/vrouter#204]
I'd like to be able to append a hash parameter to a url on user action without causing a page reload.  Widget rebuild is fine, but nothing that destructs the current widget tree.  Ideally functionality identical to [Javascript History.pushState()](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState).  Currently the only option that I can find is to use `to()`, and with or without `isReplacement` it seems to force a full page navigation w/ widget destruction.

**Comment by solwey-wes** [comment]
@lulupointu Is there any possibility of getting this functionality? :)

**Comment by lulupointu** [comment]
This is because if the url changes than `VRouter` considers that the `VWidget` is different.

To prevent this, you can use a `key` on the `VWidget` where you have a changing path.

Feel free to reopen this issue if you are having trouble implementing this.
