### ISSUE TITLE
VRouter Crashing when reloading web page

### ISSUE THREAD

**Issue by felixwortmann** [lulupointu/vrouter#21]
### Problem
My Web App crashes when I reload the Web page in the browser. I get this error:
```
For a more detailed help message, press "h". To quit, press "q".
Error: Expected a value of type 'String?', but got one of type 'LinkedMap<dynamic,
dynamic>'
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5334:11)
    at Object.castError (http://localhost:5000/dart_sdk.js:5305:15)
    at Object.cast [as as] (http://localhost:5000/dart_sdk.js:5621:17)
    at dart.NullableType.new.as (http://localhost:5000/dart_sdk.js:7182:60)
    at Function.getHistoryState
    (http://localhost:5000/packages/vrouter/src/web_helpers.dart.lib.js:1911:27)
    at main.VRouterState.new.<anonymous>
    (http://localhost:5000/packages/vrouter/src/web_helpers.dart.lib.js:4744:201)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:5000/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:5000/dart_sdk.js:39083:7)
    at simple_url_handler.SimpleRouterDelegate.new.<anonymous>
    (http://localhost:5000/packages/vrouter/src/web_helpers.dart.lib.js:4741:24)
    at simple_url_handler.SimpleRouterDelegate.new.setNewRoutePath
    (http://localhost:5000/packages/simple_url_handler/simple_url_handler.dart.lib.js:81
    7:19)
    at simple_url_handler.SimpleRouterDelegate.new.setInitialRoutePath
    (http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:19193:21
    )
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:38889:58)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:34315:23)
    at http://localhost:5000/dart_sdk.js:34252:39
    at SynchronousFuture.new.then
    (http://localhost:5000/packages/flutter/src/foundation/synchronous_future.dart.lib.j
    s:54:22)
    at _Future.new.[_chainForeignFuture] (http://localhost:5000/dart_sdk.js:34248:18)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:34494:44)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback
    (http://localhost:5000/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:39182:13)
    at http://localhost:5000/dart_sdk.js:34689:9
```
It works before reloading the web page and on mobile platforms. Am I doing something wrong or is it a problem with the library?
### This is my Code:
```dart
VRouter(
        debugShowCheckedModeBanner: false,
        localizationsDelegates: LOCALIZATION_DELEGATES,
        supportedLocales: SUPPORTED_LOCALES,
        routes: [
          VStacked(
            path: "/",
            name: "/",
            widget: MaterialAppFrame(child),
          ),
          VStacked(
            path: "/invite",
            widget: InvitePage(),
          ),
        ],
        darkTheme: ThemeService.darkTheme,
        theme: ThemeService.lightTheme,
        themeMode: ThemeService().getThemeMode(data()),
      );
```

### Versions
- flutter: 2.0.2 Stable
- vrouter: ^1.0.0-nullsafety.11 (also tried with 0.0.15, same thing happens)

**Comment by lulupointu** [comment]
This issue comes from the library, I though I solved it already but I will have a look !

**Comment by lulupointu** [comment]
Are you using `replaceHistoryState` at some point?

**Comment by felixwortmann** [comment]
No, I am not using the history at all

**Comment by lulupointu** [comment]
Can you reproduce the error inconstantly ?

If so could you give me the output of `history.state` in the chrome inspector (`Ctrl+Maj+i`)?

![image](https://user-images.githubusercontent.com/5128921/111147899-48027100-858b-11eb-9556-29c01cf9955c.png)

**Comment by felixwortmann** [comment]
The error happens every time I reload.<br>
This is the output of history.state before the reload:<br>
<img width="552" alt="image" src="https://user-images.githubusercontent.com/45035656/111150422-5dc56580-858e-11eb-9651-810f2e08635b.png">

**Comment by lulupointu** [comment]
This happens every time you reload, no matter were you navigate?

All the rest of the navigation works? 

Can you check if `history.state` is different if you try navigating before reloading ?

**Comment by felixwortmann** [comment]
When I navigate to another page and reload there, I do not get an error. The output of `history.state` is also different:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/45035656/111156028-8ef56400-8595-11eb-94cf-4f6e3cfe0c71.png">

**Comment by lulupointu** [comment]
Well that's a good sign at least. I think I know where the error comes from. It happens when you first load the app (and are on `"/"`) right?

**Comment by felixwortmann** [comment]
Yes exactly

**Comment by felixwortmann** [comment]
I am on `/#/` actually but that is just flutters `/` I guess

**Comment by lulupointu** [comment]
Yes that's right. Perfect I will fix that and get back to you!

**Comment by felixwortmann** [comment]
Thanks a lot

**Comment by lulupointu** [comment]
I'm sorry but I can still not reproduce the error.

The ideal would be if you could share your entire code? Or at least a minimal reproducible example?

**Comment by felixwortmann** [comment]
Unfortunately I can not share my entire code. I did create an example [here](https://github.com/felixwortmann/vrouter_min_rep_example) though. While trying to reproduce the error myself I think it has to do with another `MaterialApp` which I nested below the VRouter. Please take a look yourself. Just run it with `flutter run -d chrome` and reload the page

**Comment by lulupointu** [comment]
Oh I was going to ask you about that, this is definitely the issue!

Please see: https://vrouter.dev/guide/Essentials/About%20MaterialApp
