### ISSUE TITLE
The VRouteRedirector freeze the website on the splash screen

### ISSUE THREAD

**Issue by AbdelrahmanMohamedEmam** [lulupointu/vrouter#25]
When i use the VRouteRedirector to route any unexpected routes it freeze the website on the splash screen.

**Comment by AbdelrahmanMohamedEmam** [comment]
`        routes: [
          VRouteRedirector(
            // This matches any path
            path: ':_(.*)',
            // We redirect to /login
            redirectTo: '/',
          ),
        
          VStacked(
            path: '/',
            widget: LayoutTemplate(child: HomeView()),
          ),

          VStacked(
            path: '/store',
            widget: LayoutTemplate(child: StoreView()),
            subroutes: [
              VStacked(
                path: '/products',
                widget: LayoutTemplate(child: ProductView()),
              )
            ],
          ),
],`

**Comment by AbdelrahmanMohamedEmam** [comment]
`        routes: [
          VRouteRedirector(
            // This matches any path
            path: ':_(.*)',
            // We redirect to /login
            redirectTo: '/store',
          ),
        
          VStacked(
            path: '/',
            widget: LayoutTemplate(child: HomeView()),
          ),

          VStacked(
            path: '/store',
            widget: LayoutTemplate(child: StoreView()),
            subroutes: [
              VStacked(
                path: '/products',
                widget: LayoutTemplate(child: ProductView()),
              )
            ],
          ),],`

**Comment by AbdelrahmanMohamedEmam** [comment]
`
        routes: [
          VRouteRedirector(
            // This matches any path
            path: ':_(.*)',
            // We redirect to /login
            redirectTo: '/store',
          ),
        
          VStacked(
            path: '/',
            widget: LayoutTemplate(child: HomeView()),
          ),

          VStacked(
            path: '/store',
            widget: LayoutTemplate(child: StoreView()),
            subroutes: [
              VStacked(
                path: '/products',
                widget: LayoutTemplate(child: ProductView()),
              )
            ],
          ),
],
`

**Comment by lulupointu** [comment]
Vrouter uses a first match policy. This means that if you use `. *` as your first path,it will always match therefore creating an infinity loop.

**The solution** is to put this `VRouteRedirector`as the last element of the `routes` list.

**Comment by AbdelrahmanMohamedEmam** [comment]
Thanks alot it worked.
```
 VRouter(
 
        theme: ThemeData(
          primaryColor: Colors.black,
          accentColor: Colors.white,
          fontFamily: "ArcadeClassic",
        ),
        locale: _locale,
        supportedLocales: [
          Locale('en'),
          Locale('ar'),
        ],
        localizationsDelegates: [
          DemoLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        localeResolutionCallback: (deviceLocale, supportedLocales) {
          for (var locale in supportedLocales) {
            if (locale.languageCode == deviceLocale.languageCode &&
                locale.countryCode == deviceLocale.countryCode) {
              return deviceLocale;
            }
          }
          return supportedLocales.first;
        },
        routes: [
 
          VStacked(
            path: '/',
            widget: LayoutTemplate(child: HomeView()),
          ),
          VRouteRedirector(
            path: ':_(.*)',
            redirectTo: '/',
          ),
        ],
        debugShowCheckedModeBanner: false,
      ),
```

**Comment by AbdelrahmanMohamedEmam** [comment]
Is there any way to remove the /#/ from the url?

**Comment by lulupointu** [comment]
Change VRouter.mode:

```dart
VRouter(mode: VRouterMode.history, routes: ...)
```

Also I suggest you to look at [vrouter.dev](https://vrouter.dev), there are a lot of information about these subjects.

**Comment by AbdelrahmanMohamedEmam** [comment]
Thank you so much it worked.
