### ISSUE TITLE
Would be nice to have less boilerplate/indents when using VGuard with a single route

### ISSUE THREAD

**Issue by esDotDev** [lulupointu/vrouter#35]
I think I understand the benefits of allowing multiple routes for a shared guard, but the current approach seems to hurt readability quite a bit when your use cases are simpler.

For example:
```
VGuard(
  beforeEnter: (_) async {
    getModel().currentPage = HomePage.path;
    getModel().currentId = navKey.currentState!.pathParameters["id"];
  },
  stackedRoutes: [
    VWidget(
      aliases: [HomePage.path],
      path: HomePage.path + "/:id",
      widget: HomePage(),
    ),
  ],
),
```

Would be grokked more easily as:
```
VGuardSingle(
  path: HomePage.path + "/:id",
  aliases: [HomePage.path],
  beforeEnter: (_) async {
    getModel().currentPage = HomePage.path;
    getModel().currentId = navKey.currentState!.pathParameters["id"];
  },
  widget: HomePage(),
),
```

Not only is it 4 lines shorter, and saves 1 indentation level. But it allows you to put the path first, which helps the eye follow the code.

**Comment by lulupointu** [comment]
Hi,

I understand the concern but I would rather follow flutter principle "prefer composition over I heritance". 

Ideally I would like to allow you to extends a VRouteElement (as Flutter does) to allow you to easily create a custom VRouteElement.

**Comment by esDotDev** [comment]
This wouldn't require inheritence, just a wrapper that composes VGuard + VWidget.

Certainly we could do this ourselves, I just thought it might be some nice sugar for the framework, especially considering 1:1 guard:route is probably a fairly common use case.

**Comment by lulupointu** [comment]
This is fairly common but I would have to do:
* One for `VPage`
* One for `VWidget`
* One for `VNesterPage`
* One for `VNester`

This is where the Flutter approach is very powerful, no redondances in the framework so no many things to learn but infinite possibilities for devs

**Comment by theweiweiway** [comment]
I kinda like how separated it is right now - a wrapper that composes VGuard
 + VWidget could work, but I think it also might add confusion

**Comment by lulupointu** [comment]
No problem it's great to have more inputs. Also this has already been discussed [here] (https://github.com/lulupointu/vrouter/issues/13) and I think this turned out pretty well, I am always open to more opinions.

**Comment by esDotDev** [comment]
Yes, I understand the desire to avoid a ton of classes. But should be noted that it's optimizing for simplicity for beginners, and less work for maintainer, but the sacrifice is readability. It's the same kind of reason Container exists, that just combined multiple widgets in 1, its totally not necessary, but it reads better.

Anyways, we can implement ourselves so it's no big deal, thanks for the great package!

**Comment by lulupointu** [comment]
I hear you and understand your point of view. I change the package to be more flutter like with the input of several people so I will stay on this spirit for now.  

However as you know the Flutter team is currently having experience and non experience people conducting the navigation study using vrouter. I have ask to have as much raw input as possible. If I see that what you are asking come in the research study I might reconcider. 
I will keep this issue open for the time being and come to you with my findings. 

Anyone having something to say on this might also drop a comment on this issue!

**Comment by lulupointu** [comment]
Hey, I don't know if you are still following this but for anyone who might be interesting this is possible in `VRouter >= v1.1.1`.

You will have to create you own class but this way you can do whatever you want!

Here is a basic example, the trick is to extend `VRouteElementBuilder`:

```dart
class VWidgetGuarded extends VRouteElementBuilder {
  final String? path;
  final Widget widget;
  final Future<void> Function(VRedirector vRedirector)? _beforeEnter;

  VWidgetGuarded({
    required this.path,
    required this.widget,
    Future<void> Function(VRedirector vRedirector)? beforeEnter,
  }) : _beforeEnter = beforeEnter;

  @override
  List<VRouteElement> buildRoutes() => [
        VGuard(
          beforeEnter: _beforeEnter ?? (_) async {},
          stackedRoutes: [
            VWidget(
              path: path,
              widget: widget,
            ),
          ],
        ),
      ];
}
```

Which can then be used like a regular `VRouteElement`:
```dart
VRouter(
  routes: [
    VWidgetGuarded(
      beforeEnter: (_) async => print('beforeEnter in home!'),
      path: '/home',
      widget: Text('home'),
    ),
  ],
)
```

You can do even more elegant, since `VRouteElementBuilder` has a `beforeEnter` method, you can also override it directly:

```dart
class VWidgetGuarded extends VRouteElementBuilder {
  final String? path;
  final Widget widget;
  final Future<void> Function(VRedirector vRedirector)? _beforeEnter;

  VWidgetGuarded({
    required this.path,
    required this.widget,
    Future<void> Function(VRedirector vRedirector)? beforeEnter,
  }) : _beforeEnter = beforeEnter;

  @override
  List<VRouteElement> buildRoutes() => [
        VWidget(
          path: path,
          widget: widget,
        ),
      ];

  @override
  Future<void> beforeEnter(VRedirector vRedirector) async => _beforeEnter?.call(vRedirector);
}
```

Small project might not use this, but readability is not an issue then.
Bigger project can you this new way of creating `VRouteElement` extensively to greatly improve the readability, just like we are used to breaking things in different widgets.

I think this is the best middle ground there is between redundancy and readability.

**Comment by esDotDev** [comment]
Very nice! Indeed this would be well worth it in a large app if readability of the routing table is important (and it definitely is imo).
