### ISSUE TITLE
VRouter initialUrl is wrong if whole MaterialApp is rebuilding

### ISSUE THREAD

**Issue by mordivgor** [lulupointu/vrouter#39]
Hello,

I am struggling with this problem for a days and I can't figure out how to handle it..

I have StreamProvider above VRouter in widget tree - StreamProvider listen for logged in / logged out user
I have VGuard which redirects anonymous user to /login page.
I have VGuard which redirects logged in user to '/' if user wants to go '/login'.

My scenario is:
1) I am opening application with initialUrl '/' and VGuard succesfully redirects me to '/login'
2) I log in and StreamProvider executes rebuilding of VRouter - it leds me to the situation when I have url with '/login', but VRouter thinks it is in '/', so application has url '/login', but it shows page of '/'. It means that the second VGuard can't redirect user properly to '/', because VRouter thinks that user is right now at '/'.

Probably it could be a general limitation - of course VRouter can't know about rebuilding, but not sure what is underneath - maybe it is possible to get "real" url somehow?

I have quite advanced application, so I can't provide right now the simple code. I will try my best to prepare reproducible example in few days, but I am raising this issue because you may know how to handle it based on my description.

**Comment by lulupointu** [comment]
It is hard to see without the code, only the `VRouter` configuration + where is the wrapping stream would help me greatly.

In the meantime, I can maybe give you two things to try:
1. If you think the `initialUrl` is the issue, can't you change it when rebuilding `VRouter`
2. What about not rebuilding `VRouter` ? If you want to wrap everything **but** `VRouter` you can use `VRouter.builder` like so:

```dart
VRouter(
    builder: (_, child) {
      return StreamBuilder(builder: (_, __) {
        return child!;
      });
    },
}
```

**Comment by mordivgor** [comment]
Hello,

Thank you for the response!

Regarding your questions:
1. I need to check :) However, it means I need to manually parsing real URL by using some custom method to provide proper initialUrl.
2. I have checked it, but it is race condition - pushing to new route need to be before or after logout - before causes that is not going to login screen (because it is still logged in), after causes that user sees the same page as logout (which makes some problems with visibility)

Generally, I tried to simplify this problem and I have create such code:

```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:provider/provider.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (providerContext) => LoginCubit(),
      child: BlocBuilder<LoginCubit, bool>(
        builder: (context, state) {
          return VRouter(
            routes: [
              VGuard(
                beforeEnter: (vRedirector) async {
                  if (state) {
                    return vRedirector.push('/');
                  }
                },
                stackedRoutes: [
                  VWidget(
                    path: '/login',
                    widget: LoginPage()
                  ),
                ]
              ),
              VGuard(
                beforeEnter: (vRedirector) async {
                  if (!state) {
                    return vRedirector.push('/login');
                  }
                },
                stackedRoutes: [
                  VWidget(
                    path: '/',
                    widget: TargetPage()
                  ),
                ]
              )
            ],
        );
        },
      )
    );
  }
}

class LoginPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: RaisedButton(
        child: Text('Login'),
        onPressed: () => context.read<LoginCubit>().login()
      )
    );
  }
}

class TargetPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: RaisedButton(
        child: Text('Logout'),
        onPressed: () => context.read<LoginCubit>().logout()
      )
    );
  }
}

class LoginCubit extends Cubit<bool> {
  LoginCubit() : super(false);

  void login() => emit(true);
  void logout() => emit(false);
}

```

However, in this case when you click "login" it does nothing - state is updated to "true", but VGuard is not executed. It is not maybe the same problem, but it shows the problem with rebuilding the VRouter.

I could move it under VRouter, but then I am in the situation when user has blinking page - logout causes rebuilding the page (with logout user) and then I can push route to '/login'.

Any idea how to generally resolve such scenario?

**Comment by lulupointu** [comment]
I understand you issue and you are right, the issue caused by `initialUrl` would disappear if it was any but the first screen, so the problem is not as big as it might appear.

In any case, I would advice against rebuilding `VRouter` as I told you.
Here is a solution for you problem;

```dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:provider/provider.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final vRouterKey = GlobalKey<VRouterState>();
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (providerContext) => LoginCubit(vRouterKey),
      child: Builder(
        builder: (BuildContext context) {
          return VRouter(
            key: vRouterKey,
            routes: [
              VGuard(
                  beforeEnter: (vRedirector) async {
                    if (context.read<LoginCubit>().state) {
                      return vRedirector.push('/');
                    }
                  },
                  stackedRoutes: [
                    VWidget(path: '/login', widget: LoginPage()),
                  ]),
              VGuard(
                  beforeEnter: (vRedirector) async {
                    if (!context.read<LoginCubit>().state) {
                      return vRedirector.push('/login');
                    }
                  },
                  stackedRoutes: [
                    VWidget(path: '/', widget: TargetPage()),
                  ])
            ],
          );
        },
      ),
    );
  }
}

class LoginPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: RaisedButton(
            child: Text('Login'), onPressed: () => context.read<LoginCubit>().login()));
  }
}

class TargetPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: RaisedButton(
            child: Text('Logout'), onPressed: () => context.read<LoginCubit>().logout()));
  }
}

class LoginCubit extends Cubit<bool> {
  final GlobalKey<VRouterState> vRouterKey;
  LoginCubit(this.vRouterKey) : super(false);

  void login() {
    emit(true);
    vRouterKey.currentState?.push('/');
  }

  void logout() {
    vRouterKey.currentState?.push('/login');
    emit(false);
  }
}
```

I really like this one because everyone is doing its job, `VGuard` only guards while `Cubit` handles the state (which navigation is part of).

However you might not like the fact that a `GlobalKey`, which is part of flutter, comes near your state. In that case you can also use the following solution:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:provider/provider.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => LoginCubit(),
      child: Builder(
        builder: (BuildContext context) {
          return VRouter(
            builder: (context, child) {
              return BlocListener<LoginCubit, bool>(
                listener: (_, isLoggedIn) {
                  context.vRouter.push((isLoggedIn) ? '/' : '/login');
                },
                child: child,
              );
            },
            routes: [
              VGuard(
                beforeEnter: (vRedirector) async {
                  if (context.read<LoginCubit>().state) {
                    return vRedirector.push('/');
                  }
                },
                stackedRoutes: [
                  VWidget(path: '/login', widget: LoginPage()),
                ],
              ),
              VGuard(
                beforeEnter: (vRedirector) async {
                  if (!context.read<LoginCubit>().state) {
                    return vRedirector.push('/login');
                  }
                },
                stackedRoutes: [
                  VWidget(path: '/', widget: TargetPage()),
                ],
              )
            ],
          );
        },
      ),
    );
  }
}

class LoginPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: RaisedButton(
            child: Text('Login'), onPressed: () => context.read<LoginCubit>().login()));
  }
}

class TargetPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: RaisedButton(
            child: Text('Logout'), onPressed: () => context.read<LoginCubit>().logout()));
  }
}

class LoginCubit extends Cubit<bool> {
  LoginCubit() : super(false);

  void login() => emit(true);

  void logout() => emit(false);
}
```

This one avoids that your `Cubit` is polluted, also I'm not sure this will scale as well.
(**NOTE**: the second option did not work because of a bug, I had to push an update so be sure to be on VRouter>=1.1.0+19)

**Comment by mordivgor** [comment]
Thank you very much for your support!
I will check above way in my application. From my side this issue can be closed right now - please decide whether you want to keep it open before the update which you mentioned.

**Comment by lulupointu** [comment]
The update is pushed so if this works for you this can be closed
