### ISSUE TITLE
Can we access pathParameters in stateful widget's initState()?

### ISSUE THREAD

**Issue by satvikreddy** [lulupointu/vrouter#40]
In many cases we would like to set some initial state based on the pathParameters.

Trying to access context.vRouter in initState throws Error.

As a workaround, I added code to didChangeDependencies() lifecycle method and added a single run check. 
Wondering if there is a way to access vRouter in initState() method itself? This would solve many use cases.

Thanks in advance.

**Comment by lulupointu** [comment]
You can often solve this by using a builder, have a look at [this code](https://github.com/flutter/uxr/blob/317ec6e5799d6732a44b0c313cc2183b9382240a/nav2-usability/scenario-code/deeplink-pathparam/deeplink_pathparam_vrouter.dart#L39)

Would that work for you ?

**Comment by satvikreddy** [comment]
Yes, this works!

Would be great if this example could be incorporated in the [pub.dev](https://pub.dev/packages/vrouter) documentation.

**Comment by lulupointu** [comment]
I plan to link those examples in [vrouter.dev](https://vrouter.dev). I'm just waiting for all examples to be done (which depends on the flutter team as well).
