### ISSUE TITLE
Back Button: What's the best way to decide show/hide back button

### ISSUE THREAD

**Issue by TXrDev** [lulupointu/vrouter#43]
Imagine user landed on the home screen and then navigates deep into nested pages. Somewhere at your appBar builder methods you'll want to read whether there are any screens that you can pop back to to show "BACK" button. One of the option is by using historyState, but seems like it was intended for other purposes.
![image](https://user-images.githubusercontent.com/3837521/114511210-4a1a2700-9c40-11eb-9857-584a3a6feaa5.png)

**Comment by lulupointu** [comment]
I think `Navigator.canPop(context)` should work. This is how `BackButton` works actually.

**Comment by lulupointu** [comment]
Hi, is this working for you ?

**Comment by TXrDev** [comment]
That works! Thanks, @lulupointu!
