### ISSUE TITLE
Navigator.pop(ctx) not closing drawer

### ISSUE THREAD

**Issue by Donk3ys** [lulupointu/vrouter#44]
Im building a web app that uses both drawer and endDrawer in the same page.
Therefore i cant use the function `Scaffold.of(ctx).openEndDrawer()` or `scaffoldKey.currentState.openEndDrawer()` to close the Drawer or vice versa.

Im trying to use `Navigator.pop(ctx)` to close the drawer, but its not closing the Drawer as it should.

**Comment by lulupointu** [comment]
I dreaded this day will come.
I have no way of solving this right now. The drawer has a close method but it is not public.

I am going to look into this a bit more and see if I can finally solve this issue.

**Comment by Donk3ys** [comment]
Thanks so much for the quick reply... You have build an awesome user friendly package here.
Its so strange to me that Flutter doesnt have a public method for closing drawers...

**Comment by lulupointu** [comment]
Oh I think I did find a solution !

Can you try this:

```dart
context.findRootAncestorStateOfType<DrawerControllerState>()?.close()
```

Disclaimer: `findRootAncestorStateOfType` should not be called a lot, it's ok for a button press but avoid calling it in a build method for example.

If this works I think you should use this. I have a lot of work right now so if that's ok for you I would rather not spend time fixing this right now.

**Comment by Donk3ys** [comment]
You a legend,works perfectly.
