### ISSUE TITLE
Not an issue, just a question [Behavior web vs. mobile]

### ISSUE THREAD

**Issue by Aerofluxx** [lulupointu/vrouter#45]
Edit: Achieved everything from my "list" in this post. Solutions are below... Thanks a ton @lulupointu! 

Hello,

first I'm sorry I'm raising an issue but I'ld like to ask some question about VRouter, because this looks very handy for my needs.

On my research for a new navigation system for our productive application I've stumbled over VRouter.

Tried around for quiet a few hours now and still asking me:

- same navigation concept for mobile / desktop / web ✅

- for web having URL's to browse to the page with an link ✅

- different route behavior mobile vs. desktop / web ✅
  - on web / desktop there is enough space for **drawer**, a **list**, **detail** selected from list
  - on tablet there is enough space for a **list** and the **detail** selected, drawer is reachable with the appbar
  - on mobile there is space for the **list** and by tapping an item it should **push** to the **detail** view
  - so the behaviour on selecting an item on mobile is **different** to the other systems

- nested navigation - i don't want to rebuild the drawer each time I click on the lists view the details of this item ✅
  - nesting works great for my need but everything around is rebuilding everytime

- transitions should be deactivateable (most approaches I've gone through are possible to do this) ✅
- route guards to check if the user is able to load this page ✅

Could you maybe help me achieve this goals?
Thanks a ton!

**Comment by lulupointu** [comment]
> different route behavior mobile vs. desktop / web

Here is a small example showcasing what you want to achieve:

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(BooksApp());
}

class Book {
  final String title;
  final String description;

  Book(
    this.title,
    this.description,
  );
}

class BooksApp extends StatelessWidget {
  final List<Book> books = [
    Book('Stranger in a Strange Land',
        'It tells the story of Valentine Michael Smith, a human who comes to Earth in early adulthood after being born on the planet Mars and raised by Martians, and explores his interaction with and eventual transformation of Terran culture. '),
    Book('Foundation',
        'The premise of the stories is that, in the waning days of a future Galactic Empire, the mathematician Hari Seldon spends his life developing a theory of psychohistory, a new and effective mathematical sociology'),
    Book('Fahrenheit 451',
        'The novel has been the subject of interpretations focusing on the historical role of book burning in suppressing dissenting ideas for change'),
  ];

  @override
  Widget build(BuildContext context) {
    return VRouter(
      routes: [
        VWidget(
          path: '/',
          widget: BooksListScreen(books: books),
          stackedRoutes: [
            VWidget(
              path: r'book/:id(\d+)',
              widget: Builder(
                builder: (context) => BookDetailsScreen(
                  book: books[int.parse(context.vRouter.pathParameters['id']!)],
                ),
              ),
            ),
          ],
        ),
        VRouteRedirector(path: ':_(.+)', redirectTo: '/'),
      ],
    );
  }
}

class BooksListScreen extends StatefulWidget {
  final List<Book> books;

  BooksListScreen({required this.books});

  @override
  _BooksListScreenState createState() => _BooksListScreenState();
}

class _BooksListScreenState extends State<BooksListScreen> {
  final drawer = Drawer(child: Text('This is a useless Drawer'));

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        final isMobile = (constraints.maxWidth < 800);
        final isTablet = (constraints.maxWidth < 1000);
        return Scaffold(
          appBar: AppBar(
            title: Text(isTablet ? (isMobile ? "Mobile mode" : "Tablet mode") : "Web mode"),
            centerTitle: true,
          ),
          drawer: isTablet ? drawer : null,
          body: Row(
            children: [
              if (!isTablet) drawer,
              Flexible(
                child: ListView(
                  children: [
                    for (var book in widget.books)
                      ListTile(
                        title: Text(book.title),
                        subtitle: !isMobile ? Text(book.description) : null,
                        onTap: isMobile
                            ? () => context.vRouter.push('/book/${widget.books.indexOf(book)}')
                            : null,
                      )
                  ],
                ),
              ),
            ],
          ),
        );
      },
    );
  }
}

class BookDetailsScreen extends StatelessWidget {
  final Book book;

  BookDetailsScreen({
    required this.book,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(book.title, style: Theme.of(context).textTheme.headline6),
            Text(book.description, style: Theme.of(context).textTheme.subtitle1),
          ],
        ),
      ),
    );
  }
}
```

Here is a video of it in action:
![vrouter_adaptative](https://user-images.githubusercontent.com/5128921/114752533-aff8d280-9d56-11eb-8eda-0c9d92a4c7ce.gif)

Don't copy the value for `tabletMode` or `mobileMode`, this was just for the demo. 
Apart from that everything is real and achieve what you described if I understood well

**Comment by lulupointu** [comment]
> nested navigation - i don't want to rebuild the drawer each time I click on the lists view the details of this item

I am not sure of the problem you are referring to here. If your issue is that your widget are rebuilding, please read this: https://stackoverflow.com/a/52249579/5990125

The important thing is:
> The build method is designed in such a way that it should be pure/without side effects

This is an important concept of flutter, if this is your issue, then the issue is not `VRouter` but rather what your are doing in your `build` methods.

If this is not your issue, could you elaborate because I did not understand what it is?

**Comment by Aerofluxx** [comment]
> ### Different route behavior mobile vs. desktop / web
> Here is a small example showcasing what you want to achieve:
> 
> .....


This is already a very helpful post, **thanks a lot!**
Maybe this is also a "quick" one for you?

I've tried to make a video for a better understanding based on your first answer. 💯 
![Kapture 2021-04-14 at 19 42 07](https://user-images.githubusercontent.com/62898978/114755110-973dec00-9d59-11eb-8fc4-c73fb520a552.gif)



> ### Nested navigation - i don't want to rebuild the drawer each time I click on the lists view the details of this item
> I am not sure of the problem you are referring to here. If your issue is that your widget are rebuilding, please read this: https://stackoverflow.com/a/52249579/5990125
> .....


> 
> If this is not your issue, could you elaborate because I did not understand what it is?

Yes I know and I'm also developing with Remi's posts in mind 😉 
Maybe my brain is too much into "lesser builds" things ... sorry

**Comment by lulupointu** [comment]
In "much more place for detail", you want a static thing (like all the details) or you want the detail of the book you click on?

**Comment by Aerofluxx** [comment]
Like in the drawer on mobile, there should only be the title in the list, and the details of the book should be in "much more place for detail".

**Comment by lulupointu** [comment]
Here is a working of what you are trying to achieve:

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(BooksApp());
}

class Book {
  final String title;
  final String description;

  Book(
    this.title,
    this.description,
  );
}

class BooksApp extends StatelessWidget {
  final List<Book> books = [
    Book('Stranger in a Strange Land',
        'It tells the story of Valentine Michael Smith, a human who comes to Earth in early adulthood after being born on the planet Mars and raised by Martians, and explores his interaction with and eventual transformation of Terran culture. '),
    Book('Foundation',
        'The premise of the stories is that, in the waning days of a future Galactic Empire, the mathematician Hari Seldon spends his life developing a theory of psychohistory, a new and effective mathematical sociology'),
    Book('Fahrenheit 451',
        'The novel has been the subject of interpretations focusing on the historical role of book burning in suppressing dissenting ideas for change'),
  ];

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        final isMobile = (constraints.maxWidth < 800);

        return VRouter(
          routes: [
            VWidget(
              path: '/',
              aliases: [if (!isMobile) r'/book/:id(\d+)'],
              key: ValueKey('BooksListScreen'),
              widget: Builder(builder: (context) {
                final selectedBookId = int.tryParse(context.vRouter.pathParameters['id'] ?? '');
                final selectedBook = selectedBookId != null ? books[selectedBookId] : null;
                return BooksListScreen(books: books, selectedBook: selectedBook);
              }),
              stackedRoutes: [
                if (isMobile)
                  VWidget(
                    path: r'book/:id(\d+)',
                    widget: Builder(
                      builder: (context) => BookDetailsScreen(
                        book: books[int.parse(context.vRouter.pathParameters['id']!)],
                      ),
                    ),
                  ),
              ],
            ),
            VRouteRedirector(path: ':_(.+)', redirectTo: '/'),
          ],
        );
      },
    );
  }
}

class BooksListScreen extends StatefulWidget {
  final List<Book> books;
  final Book? selectedBook;

  BooksListScreen({required this.books, required this.selectedBook});

  @override
  _BooksListScreenState createState() => _BooksListScreenState();
}

class _BooksListScreenState extends State<BooksListScreen> {
  final drawer = Drawer(child: Text('This is a useless Drawer'));

  @override
  Widget build(BuildContext context) {
    print('build BooksListScreen');
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        final isMobile = (constraints.maxWidth < 800);
        final isTablet = (constraints.maxWidth < 1000);
        return Scaffold(
          appBar: AppBar(
            title: Text(isTablet ? (isMobile ? "Mobile mode" : "Tablet mode") : "Web mode"),
            centerTitle: true,
          ),
          drawer: isTablet ? drawer : null,
          body: Row(
            children: [
              if (!isTablet) drawer,
              Flexible(
                child: ListView(
                  children: [
                    for (var book in widget.books)
                      ListTile(
                        title: Text(book.title),
                        onTap: () => context.vRouter.push('/book/${widget.books.indexOf(book)}'),
                      )
                  ],
                ),
              ),
              if (!isMobile)
                Flexible(
                  child: Center(
                    child: Text(
                      widget.selectedBook?.description ??
                          'Tap on a book to see its description',
                    ),
                  ),
                )
            ],
          ),
        );
      },
    );
  }
}

class BookDetailsScreen extends StatelessWidget {
  final Book book;

  BookDetailsScreen({
    required this.book,
  });

  @override
  Widget build(BuildContext context) {
    print('build BookDetailsScreen');
    return Scaffold(
      appBar: AppBar(),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(book.title, style: Theme.of(context).textTheme.headline6),
            Text(book.description, style: Theme.of(context).textTheme.subtitle1),
          ],
        ),
      ),
    );
  }
}
```

This remain simple enough, however if this gets too complex you might have to do more separate router settings.
I don't feel like this is an issue since the same happens with widget: until some point you can make then adapt to different screen size, but there come a point where you must have separate widget for separate screen size. Really depends on your app then !

**Comment by Aerofluxx** [comment]
The solution for resize from mobile to tablet will be something like reacting to the switch and use a 
`context.vRouter.pop();` only in detail views.

That's it ... All of your answers where perfect. Thank you so so much!

Do you have an patreon link or anything?

**Comment by lulupointu** [comment]
> Do you have an patreon link or anything?

Nothing but your thanks are enough 😉!

**Comment by Aerofluxx** [comment]
Hey @lulupointu :) 

Maybe you can help me out again? 

Just came across a change (maybe) that the above system is not working anymore.

Like in [https://github.com/lulupointu/vrouter/issues/62](https://github.com/lulupointu/vrouter/issues/62) after the update from `vrouter: ^1.1.0+20` to `vrouter: ^1.1.2+5` the described behavior from above is not the same.

At the moment, if I resize my app from Desktop to mobile the "desktop behavior" is still "used".
If I refresh at the screen size at mobile now, the "mobile behavior" is used.

It looks like resizing the screen doesn't change the `VWidget` in my routers dynamically...

Maybe you have an idea where I can start from? :)
Thanks a ton ...as always. 👍

**Comment by lulupointu** [comment]
I don't have access to my computer for 3 days so I cannot test this but I will.

My two cent on this is that in order to introduce `VRouteElementBuilder` and for better performances, routes are now computed lazily and only one at most. 
This means that event if the screen size changes, routes are not computed again.

Something worth trying would be to give `VRouter` a key which changes with screen sizes. 

Let me know if this does the trick!

**Comment by lulupointu** [comment]
Also only change the key as little as possible, ie make a mobileKey and ComputerKey. This will be better for performance.

**Comment by Aerofluxx** [comment]
I've tried changing the key as less as possible by:

```
 final String _screenMode = getValueForScreenType<String>(context: context, mobile: 'MOB', tablet: 'TAB', desktop: 'DESK');

      return VRouter(
        key: ValueKey<String>('MainRouter-$_screenMode'),
        debugShowCheckedModeBanner: false,
        theme: context.select((KBThemeBloc element) => element.state.theme),
        buildTransition: (Animation<double> animation1, _, Widget child) {
          return FadeTransition(opacity: animation1, child: child);
        },
        transitionDuration: const Duration(milliseconds: 150),
        routes: <VRouteElement>[
```

But this leets do a complete "reset" of the VRouter and so to my initial route (Splash Screen)

Bringing the same idea to the `VWidget` does have no effect. Like you already said, this will not be recomputed.

**Comment by lulupointu** [comment]
I see... I'll have a look once I have access to a computer

**Comment by lulupointu** [comment]
I did not forget you, I am looking into this. I have a workaround that you could use but nothing that I can bake into VRouter right now.
This is an issue with flutter unfortunately, but I'm looking for different ways to make it work.

**Comment by lulupointu** [comment]
Fixed with `v1.1.3+2`. If this works for you you can close this :)

**Comment by lulupointu** [comment]
Actually fixed in `v1.1.4+1`, this was harder than expected.
Also you have to use **`appRouterKey`** and **not** `key`.

Please tell me if this works for you !

**Comment by Aerofluxx** [comment]
YES! :) You did it! Thanks for changing it to still support my project needs.


For others looking for the appRouterKey, I've did it like this:
```
...
 final String _screenMode = getValueForScreenType<String>(context: context, mobile: 'MOB', tablet: 'TAB', desktop: 'DESK');

      return VRouter(
        debugShowCheckedModeBanner: false,
        appRouterKey: ValueKey<String>('MainRouter-$_screenMode'),
        theme: context.select((KBThemeBloc element) => element.state.theme),
        buildTransition: (Animation<double> animation1, _, Widget child) {
          return FadeTransition(opacity: animation1, child: child);
        },
        transitionDuration: const Duration(milliseconds: 150),
        routes: <VRouteElement>[
          splashRouter(context),
          loginRouter(context),
          // VGuard protects the routes in stackedRoutes
          VGuard(
...
```

@lulupointu As always, I'm super super thankful for this routing package! For my projects (and my personal "style") it fits perfectly. And I'll keep asking you until you have it: _Do you have an patreon link or anything?_ 😉

**Comment by lulupointu** [comment]
I am curious of what you project is and eventually if you are hitting any roadblock (even minor). Maybe when you have the time and want to, you could come on [the discord channel](https://discord.gg/2mua42F66P) to discuss that 😊 !
Still no patreon though, keep insisting I might create one :smiley:

**Comment by lulupointu** [comment]
For the record, `appRouterKey` is now depreciated because it is redundant with `navigatorKey`. Here is the new way of achieving this:

```dart
class BooksApp extends StatelessWidget {
  final List<Book> books = [
    Book('Stranger in a Strange Land',
        'It tells the story of Valentine Michael Smith, a human who comes to Earth in early adulthood after being born on the planet Mars and raised by Martians, and explores his interaction with and eventual transformation of Terran culture. '),
    Book('Foundation',
        'The premise of the stories is that, in the waning days of a future Galactic Empire, the mathematician Hari Seldon spends his life developing a theory of psychohistory, a new and effective mathematical sociology'),
    Book('Fahrenheit 451',
        'The novel has been the subject of interpretations focusing on the historical role of book burning in suppressing dissenting ideas for change'),
  ];

  final mobileGlobalKey = GlobalKey<NavigatorState>();
  final computerGlobalKey = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        final isMobile = (constraints.maxWidth < 800);

        return VRouter(
          navigatorKey: isMobile ? mobileGlobalKey : computerGlobalKey,
          mode: VRouterModes.history,
          routes: [
            VWidget(
              path: '/',
              aliases: [if (!isMobile) r'/book/:id(\d+)'],
              key: ValueKey('BooksListScreen'),
              widget: Builder(builder: (context) {
                final selectedBookId = int.tryParse(context.vRouter.pathParameters['id'] ?? '');
                final selectedBook = selectedBookId != null ? books[selectedBookId] : null;
                return BooksListScreen(books: books, selectedBook: selectedBook);
              }),
              stackedRoutes: [
                if (isMobile)
                  VWidget(
                    path: r'book/:id(\d+)',
                    widget: Builder(
                      builder: (context) => BookDetailsScreen(
                        book: books[int.parse(context.vRouter.pathParameters['id']!)],
                      ),
                    ),
                  ),
              ],
            ),
            VRouteRedirector(path: ':_(.+)', redirectTo: '/'),
          ],
        );
      },
    );
  }
}
```

It's only depreciated though, so I will try to keep it as long as possible.

**Comment by chungonion** [comment]
Hi there, just some experience sharing here, for those who are going to Responsive Framework (also should work for Responsive Builder) to handling the responsive UI and integrated the routes based on the layout logic. After discussing with @lulupointu in Discord, he discovered that one could Wrap the VRouter in this way.

`MediaQuery.fromWindow(  
  child: ResponsiveWrapper.builder( 
    Builder( 
      builder: (context) { 
        return VRouter(...); 
      }, 
    ), 
  ), 
)`

and for the alias you could use the following segment
`ResponsiveValue(context, defaultValue: <String>[
   //your alias...
                      ], valueWhen: [
                        Condition.largerThan(name: TABLET, value: [
   //your alias...
                        ])
                      ]).value ??
                      <String>[
                     //your alias...
                      ],
`

Again thanks @lulupointu for your valuable assistance!
