### ISSUE TITLE
Just thanks!

### ISSUE THREAD

**Issue by CosmicPangolin** [lulupointu/vrouter#47]
I spent some time digging through this and other routing libs while comparing Nav 2.0 abstractions, and I just wanna say...this is a super well-designed declarative model with great documentation throughout.  Easily the most powerful router available in Flutter.  Been waiting on this for a long time :)

**Comment by lulupointu** [comment]
Thank you so much! 🎉🎉
There is much that I want to do to improve further the experience, especially for large projet. But I'm glad that this package helps! Don't hesitate to leave suggestions as well if you have some! 😊
