### ISSUE TITLE
Getting an error with Navigator.pop

### ISSUE THREAD

**Issue by BaronRector** [lulupointu/vrouter#5]
I'm running into an issue where I'm running Navigator.pop after my VRouter call when clicking on links in an app drawer to close the app drawer after the route call. The page changes but the drawer stays open and is producing the following error:

TypeError: Cannot read property 'length' of null
    at Function.parse (http://localhost:60034/dart_sdk.js:124821:31)
    at main.VRouterState.new._updateUrl (http://localhost:60034/packages/vrouter/src/web_helpers.dart.lib.js:5130:31)
    at _updateUrl.next (<anonymous>)
    at runBody (http://localhost:60034/dart_sdk.js:38027:34)
    at Object._async [as async] (http://localhost:60034/dart_sdk.js:38058:7)
    at main.VRouterState.new.[_updateUrl] (http://localhost:60034/packages/vrouter/src/web_helpers.dart.lib.js:5125:20)
    at main.VRouterState.new._pop (http://localhost:60034/packages/vrouter/src/web_helpers.dart.lib.js:5415:27)
    at _pop.next (<anonymous>)
    at runBody (http://localhost:60034/dart_sdk.js:38027:34)
    at Object._async [as async] (http://localhost:60034/dart_sdk.js:38058:7)
    at main.VRouterState.new.[_pop] (http://localhost:60034/packages/vrouter/src/web_helpers.dart.lib.js:5380:20)
    at http://localhost:60034/packages/vrouter/src/web_helpers.dart.lib.js:3524:47
    at navigator$.NavigatorState.new.pop (http://localhost:60034/packages/flutter/src/widgets/widget_span.dart.lib.js:23257:60)
    at Function.pop (http://localhost:60034/packages/flutter/src/widgets/widget_span.dart.lib.js:21234:40)
    at http://localhost:60034/packages/matthew_sehorn/common_widgets/appbar_drawer.dart.lib.js:640:1575
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:60034/packages/flutter/src/material/icon_button.dart.lib.js:51104:42)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:60034/packages/flutter/src/gestures/recognizer.dart.lib.js:190:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:60034/packages/flutter/src/gestures/tap.dart.lib.js:396:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:60034/packages/flutter/src/gestures/tap.dart.lib.js:202:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:60034/packages/flutter/src/gestures/tap.dart.lib.js:179:23)
    at arena.GestureArenaManager.new.sweep (http://localhost:60034/packages/flutter/src/gestures/arena.dart.lib.js:209:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:60034/packages/flutter/src/gestures/binding.dart.lib.js:319:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:60034/packages/flutter/src/gestures/binding.dart.lib.js:298:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:60034/packages/flutter/src/rendering/layer.dart.lib.js:6088:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:60034/packages/flutter/src/gestures/binding.dart.lib.js:269:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:60034/packages/flutter/src/gestures/binding.dart.lib.js:242:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:60034/packages/flutter/src/gestures/binding.dart.lib.js:231:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:60034/packages/flutter/src/gestures/binding.dart.lib.js:221:65)
    at Object.invoke1 (http://localhost:60034/dart_sdk.js:181075:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:60034/dart_sdk.js:163049:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:60034/dart_sdk.js:163684:49)
    at http://localhost:60034/dart_sdk.js:164117:26
    at http://localhost:60034/dart_sdk.js:164076:16
    at http://localhost:60034/dart_sdk.js:163784:11

**Comment by lulupointu** [comment]
Can you provide a small snippet of code?
At least your Vrouter + the part where you use pop

**Comment by BaronRector** [comment]
Yeah no problem at all

Here is the main.dart code:

`void main() {
  runApp(
    ProviderScope(
      child: VRouter(
        mode: VRouterModes.history,
        theme: ThemeData(
          fontFamily: "Poppins",
          brightness: Brightness.dark,
        ),
        debugShowCheckedModeBanner: false,
        routes: [
          VStacked(
            key: ValueKey('MyScaffold'),
            widget: MyScaffold(),
            subroutes: [
              VChild(
                path: '/',
                name: 'home',
                widget: Home(),
              ),
              VChild(
                path: '/resume',
                name: 'resume',
                widget: Resume(),
              ),
            ],
          ),
        ],
      ),
    ),
  );
}

class MyScaffold extends StatelessWidget {
  const MyScaffold({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Consumer(
        builder: (_, watch, consumerChild) {
          final isDesktop = watch(isDesktopProvider).value;
          return Scaffold(
            appBar: isDesktop ? null : appBar(),
            drawer: isDesktop ? null : AppBarDrawer(),
            backgroundColor: isDesktop ? Color(0xff007bff) : null,
            body: Container(
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: AssetImage('assets/images/main_bg.png'),
                  fit: BoxFit.cover,
                ),
              ),
              child: VRouteElementData.of(context).vChild,
            ),
          );
        },
      ),
    );
  }
}`

Here is the portion where I use the pop:

`class AppBarDrawer extends StatelessWidget {
  const AppBarDrawer({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.all(16),
      child: ClipRRect(
        borderRadius: BorderRadius.all(
          Radius.circular(12),
        ),
        child: Drawer(
          child: ListView(
            padding: EdgeInsets.zero,
            children: <Widget>[
              Container(
                color: Color(0xff222222),
                padding: const EdgeInsets.all(24.0),
                margin: EdgeInsets.only(
                  bottom: 8,
                ),
                child: Row(
                  children: [
                    appBarHeader(),
                    SizedBox(
                      width: 12,
                    ),
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Container(
                          child: SelectableText(
                            Strings.matthew,
                            style: TextStyle(
                              fontSize: 20,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                        SelectableText(
                          Strings.sehorn,
                          textAlign: TextAlign.left,
                          style: TextStyle(
                            fontSize: 20,
                          ),
                        ),
                      ],
                    )
                  ],
                ),
              ),
              AppMenuButton(
                pressedFunc: () => {
                  VRouterData.of(context).push('/'),
                  Navigator.pop(context),
                },
                label: Strings.home,
              ),
              AppMenuButton(
                pressedFunc: () => {
                  VRouterData.of(context).push('/resume'),
                  Navigator.pop(context),
                },
                label: Strings.resume,
              ),
              AppMenuButton(
                pressedFunc: () => {
                  VRouterData.of(context).push('/resume'),
                  Navigator.pop(context),
                },
                label: Strings.portfolio,
              ),
              AppMenuButton(
                pressedFunc: () => {
                  VRouterData.of(context).push('/resume'),
                  Navigator.pop(context),
                },
                label: Strings.contact,
              ),
              AppMenuButton(
                pressedFunc: () => {
                  VRouterData.of(context).push('/resume'),
                  Navigator.pop(context),
                },
                label: Strings.about,
              ),
            ],
          ),
        ),
      ),
    );
  }
}`

**Comment by lulupointu** [comment]
Using pop here does not work indeed. Instead, you should close the drawer programaticaly using `Scaffold.of(context).openEndDrawer();`

Here is a small working example based on you VRouter:

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(
    VRouter(
      mode: VRouterModes.history,
      theme: ThemeData(
        fontFamily: "Poppins",
        brightness: Brightness.dark,
      ),
      debugShowCheckedModeBanner: false,
      routes: [
        VStacked(
          key: ValueKey('MyScaffold'),
          widget: MyScaffold(),
          subroutes: [
            VChild(
              path: '/',
              name: 'home',
              widget: Home(),
            ),
            VChild(
              path: '/resume',
              name: 'resume',
              widget: Resume(),
            ),
          ],
        ),
      ],
    ),
  );
}

class MyScaffold extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Getting an error with Navigator.pop #5')),
      body: VRouteElementData.of(context).vChild,
      drawer: Drawer(
        child: ListView(
          padding: EdgeInsets.zero,
          children: <Widget>[
            DrawerHeader(
              child: Text('Drawer Header'),
              decoration: BoxDecoration(
                color: Colors.blue,
              ),
            ),
            ListTile(
              title: Text('Home'),
              onTap: () {
                VRouterData.of(context).push('/');
                Scaffold.of(context).openEndDrawer();
              },
            ),
            ListTile(
              title: Text('Resume'),
              onTap: () {
                VRouterData.of(context).push('/resume');
                Scaffold.of(context).openEndDrawer();
              },
            ),
          ],
        ),
      ),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(child: Text('Home'));
  }
}

class Resume extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(child: Text('Resume'));
  }
}
```

Even better imo would be to use a `VNavigationGuard` to call `openEndDrawer`, so that you don't have to remember calling it every time. Here is the example using `VNavigationGuard`:

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(
    VRouter(
      mode: VRouterModes.history,
      theme: ThemeData(
        fontFamily: "Poppins",
        brightness: Brightness.dark,
      ),
      debugShowCheckedModeBanner: false,
      routes: [
        VStacked(
          key: ValueKey('MyScaffold'),
          widget: MyScaffold(),
          subroutes: [
            VChild(
              path: '/',
              name: 'home',
              widget: Home(),
            ),
            VChild(
              path: '/resume',
              name: 'resume',
              widget: Resume(),
            ),
          ],
        ),
      ],
    ),
  );
}

class MyScaffold extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Getting an error with Navigator.pop #5')),
      body: VRouteElementData.of(context).vChild,
      drawer: Drawer(
        child: Builder(
          builder: (context) {
            return VNavigationGuard(
              afterUpdate: (_, __, ___) => Scaffold.of(context).openEndDrawer(),
              child: ListView(
                padding: EdgeInsets.zero,
                children: <Widget>[
                  DrawerHeader(
                    child: Text('Drawer Header'),
                    decoration: BoxDecoration(
                      color: Colors.blue,
                    ),
                  ),
                  ListTile(
                    title: Text('Home'),
                    onTap: () => VRouterData.of(context).push('/'),
                  ),
                  ListTile(
                    title: Text('Resume'),
                    onTap: () => VRouterData.of(context).push('/resume'),
                  ),
                ],
              ),
            );
          },
        ),
      ),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(child: Text('Home'));
  }
}

class Resume extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(child: Text('Resume'));
  }
}
```

If this works for you I let you close the issue !

**Comment by BaronRector** [comment]
That worked perfectly, thanks for the help!
