### ISSUE TITLE
[Question] Hey I want to use VRouter but I can't figure out how to use MultiProvider in the runApp Function.

### ISSUE THREAD

**Issue by AryashDubey** [lulupointu/vrouter#50]
I am using provider package of flutter and it requires you to use MultiProvider Function inside run app but Vrouter also requires the same. Is there any way to use both of them simultaneously

**Comment by lulupointu** [comment]
Sure! Use MultiProvider on top of VRouter.

**Comment by AryashDubey** [comment]
Yeah am glad that I figured it out myself but thank you for making such a wonderful package. You helped me a lot! And anyone else who's having the same problem can contact me!
