### ISSUE TITLE
[Question] How to show fullscreenDialog

### ISSUE THREAD

**Issue by Poweranimal** [lulupointu/vrouter#53]
I wonder how to show a page with `fullscreenDialog`.

Components like `VWidget` don't provide this option.

Only utilizing by `VBasePage` seems to allow this behavior.

Could one be so kind and share with my a best practice example in this regard?

**Comment by lulupointu** [comment]
Hi,

Just added `fullscreenDialog` attribute to `VWidget`. I think this is reasonable, I just never used it so did not think about it.

Just use `VRouter >= 1.1.1+4`

**Comment by Poweranimal** [comment]
Perfect, thank you very much!
