### ISSUE TITLE
Can I use it with getx?

### ISSUE THREAD

**Issue by miaosun009** [lulupointu/vrouter#59]
Excited to see this package, but I use GetX for my project, so I'm not sure if I can combine the two

**Comment by miaosun009** [comment]
![image](https://user-images.githubusercontent.com/17589354/117264074-74e54d00-ae85-11eb-9178-b3bb66ccfaaa.png)

I implemented the following code as you suggested, but it doesn't seem to work

**Comment by lulupointu** [comment]
I will take a look later today.

Just to be sure, you basically only have implemented what you sent me in the picture and launch the app?

**Comment by miaosun009** [comment]
@lulupointu 
Yes, the efficiency with which you responded to your questions is impressive, and this will be a promising package

**Comment by miaosun009** [comment]
@lulupointu 
Hey, I think the VRouterDelegate should expose the NavigatorKey that can be used for getX's navigation without context

![image](https://user-images.githubusercontent.com/17589354/117312004-4ed8a080-aeb7-11eb-9470-ffe886c61cb6.png)

**Comment by lulupointu** [comment]
You can use `VRouterDelegate.push` directly can't you ?

**Comment by lulupointu** [comment]
This issue is that `Get.context` is too much up the tree to have access to `VRouter` is that right?

**Comment by miaosun009** [comment]
@lulupointu nice VrouterDelegate.push is available. The next step is to combine GetX dependency injection and state management with VRouter

**Comment by lulupointu** [comment]
Concerning the issue https://github.com/lulupointu/vrouter/issues/59#issuecomment-833324602 I'm sorry but I can't reproduce your error. 

<details>
<summary>
Here is a code example
</summary>

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:vrouter/vrouter.dart';

main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {

    return GetMaterialApp.router(
      routeInformationParser: VRouteInformationParser(),
      routerDelegate: VRouterDelegate(
        routes: [
          VWidget(
            path: '/',
            widget: Builder(
                builder: (context) {
                  return TextButton(
                    onPressed: () => context.vRouter.push('/other'),
                    child: Text('/nothing'),
                  );
                }
            ),
          ),
          VWidget(
            path: '/other',
            widget: Builder(
                builder: (context) {
                  return TextButton(
                    onPressed: () => context.vRouter.push('/'),
                    child: Text('other'),
                  );
                }
            ),
          ),
        ],
      ),
      // Here is the equivalent to VRouter.routes
      backButtonDispatcher: VBackButtonDispatcher(),
    );
  }
}
```

</details>

If I run this with `vrouter: ^1.1.1+9` everything is fine

**Comment by lulupointu** [comment]
As a matter of fact I think extracting `VRouterDelegate` in a class attribute is better otherwise hot reload (on the web at least) is broken. I think this is an issue with flutter and not `VRouter` since I have seen some navigation packages having the same issue.

**Comment by lulupointu** [comment]
Concerning state management and dependency injection let me know how it goes, and if there is a specific problem I might be able to help !

**Comment by miaosun009** [comment]
@lulupointu 
Thank you very much. I think dependency injection and state management are already a problem of GET, not a problem of VRouter anymore. I just don't know how to deal with this part

[https://github.com/jonataslaw/getx/blob/master/documentation/en_US/dependency_management.md#bindingsbuilder](url)
The GET dependency injection part is strongly related to routing

**Comment by lulupointu** [comment]
`GetPage` is just a page so you could use `VPage` like so:

```dart
VPage(
  path: '/',
  pageBuilder: (LocalKey key, Widget child, String? name) => GetPage(name: name ?? '', page: () => child),
  widget: Text('Home'),
)
```

**Comment by miaosun009** [comment]
@lulupointu So how does vPage work with VRouter? 😢

**Comment by lulupointu** [comment]
`VPage` is just a `VRouteElement` so just use it instead of `VWidget`

**Comment by miaosun009** [comment]
@lulupointu  Unfortunately, it didn't work out
`
======== Exception caught by widgets library =======================================================
The following LateError was thrown building Builder:
LateInitializationError: Field 'routeTree' has not been initialized.

The relevant error-causing widget was: 
  Builder file:///Users/jason/.fvm/versions/2.0.4-stable/.pub-cache/hosted/pub.dartlang.org/vrouter-1.1.1+9/lib/src/vrouter/vrouter_delegate.dart:1288:16
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
packages/get/get_navigation/src/root/root_controller.dart 31:23               get routeTree
packages/get/get_navigation/src/extension_navigation.dart 1187:50             GetNavigation.get$35routeTree
packages/get/get_navigation/src/routes/route_middleware.dart 209:33           needRecheck
packages/get/get_navigation/src/routes/route_middleware.dart 169:12           page
...
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder:
A GlobalKey was used multiple times inside one widget's child list.

The offending GlobalKey was: [LabeledGlobalKey<NavigatorState>#aaa02]
The parent of the widgets with that key was: Builder
The first child to get instantiated with that key became: Navigator-[LabeledGlobalKey<NavigatorState>#aaa02]
  dirty
  dependencies: [_EffectiveTickerMode, UnmanagedRestorationScope, HeroControllerScope]
  state: NavigatorState#d1aae(tickers: tracking 1 ticker)
The second child that was to be instantiated with that key was: Builder
A GlobalKey can only be specified on one widget at a time in the widget tree.
The relevant error-causing widget was: 
  Builder file:///Users/jason/.fvm/versions/2.0.4-stable/.pub-cache/hosted/pub.dartlang.org/vrouter-1.1.1+9/lib/src/vrouter/vrouter_delegate.dart:1288:16
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
packages/flutter/src/widgets/framework.dart 3479:11                           <fn>
packages/flutter/src/widgets/framework.dart 3492:16                           [_retakeInactiveElement]
packages/flutter/src/widgets/framework.dart 3523:33                           inflateWidget
packages/flutter/src/widgets/framework.dart 3303:20                           updateChild
...
====================================================================================================

======== Exception caught by widgets library =======================================================
A GlobalKey was used multiple times inside one widget's child list.
The relevant error-causing widget was: 
  Builder file:///Users/jason/.fvm/versions/2.0.4-stable/.pub-cache/hosted/pub.dartlang.org/vrouter-1.1.1+9/lib/src/vrouter/vrouter_delegate.dart:1288:16
====================================================================================================
`

**Comment by lulupointu** [comment]
Can you provide a small snippet which produce this error? I think I know why this happens

**Comment by miaosun009** [comment]
```
import 'package:amber_pro_app/app_binding.dart';
import 'package:amber_pro_app/di.dart';
import 'package:amber_pro_app/modules/modules.dart';
import 'package:amber_pro_app/routes/routes.dart';
import 'package:amber_pro_app/shared/shared.dart';
import 'package:amber_pro_app/theme/theme.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get/get_navigation/src/root/parse_route.dart';
import 'package:vrouter/src/main.dart';
import 'package:vrouter/vrouter.dart';

import 'shared/config/app_config.dart';

void appStart(AppConfig config) {
  AppSentry.runWithCatchError(() async {
    await DI.init(config);
    runApp(App());
  });
}

final vRouterDelegate = VRouterDelegate(
  routes: [
    VPage(path: '/', pageBuilder: (LocalKey key, Widget child, String? name) => GetPage(name: name ?? '', page: () => child), widget: StartView()),
  ],
);

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    I18nService i18nService = Get.find();
    return GetMaterialApp.router(
      initialBinding: AppBinding(),
      debugShowCheckedModeBanner: false,
      locale: i18nService.locale,
      fallbackLocale: i18nService.fallbackLocale,
      translationsKeys: i18nService.translationsKeys,
      builder: Toast.init(),
      routerDelegate: vRouterDelegate,
      routeInformationParser: VRouteInformationParser(),
    );
  }
}

```

**Comment by lulupointu** [comment]
I'm looking into it. Seems like a lot of people have issue with `Navigator 2.0` and `Get`.

**Comment by lulupointu** [comment]
From what I see `GetPage`s are really wrapped into `getx` navigation. Therefore if you use them you must use `getx` navigation. 

I did try to find any resource for people using `GetPage` with an external navigation package but I cannot find anyone who succeeded. Maybe if you can and link me there I can help you.

That being said, I am not 100% sure `GetPage` are needed. Note those issues:
- https://github.com/jonataslaw/getx/issues/1263
-  https://github.com/jonataslaw/getx/issues/1314
- https://github.com/jonataslaw/getx/issues/446
Each time, someone is using an external Navigator package and `GetX`. Note that `GetMaterialApp.router` is used but `GetPage` is **not**.

Note however this comment: https://github.com/jonataslaw/getx/issues/77#issuecomment-626001997
jonataslaw, the author of `GetX` does not seem to really support the idea of using external packages. To me this makes sense, `GetX` controls everything: Your state, your pages, where you are and when. Managing everything allows it to be omniscient and to provide you with powerful features. However I think flexibility is the cost. Take everything or take nothing seems to be the state of mind.

Again, if you find any example that finds a what to make `GetX` work with an external `Navigation` package, I would gladly see it and help you to integrate `VRouter`!

**Comment by miaosun009** [comment]
@lulupointu Anyway, thank you very much

**Comment by miaosun009** [comment]
> 如有发现，请随时重新打开

Have you considered combining VRouter state management and dependency injection into a complete package like GetX

**Comment by lulupointu** [comment]
I don't really like the idea of locking people's choice. I would rather create a second state management package than integrate it into my navigation library.

That being said, I am using it with bloc for a large project and it works like a charm. What I might do is post recommendations on how to use VRouter with different state management packages. But this will take time and I would need some help for the state management solutions which I don't know.
