### ISSUE TITLE
Not friendly to projects that require international support

### ISSUE THREAD

**Issue by miaosun009** [lulupointu/vrouter#60]
When easy_localization is used for internationalization, after context.setLocale (Locale('en', 'US')), only the current page changes and the previous page is not refreshed. This problem does not exist when using MaterialApp directly

**Comment by lulupointu** [comment]
Hi,
I have never used this package, could you provide a small reproducible example?

**Comment by lulupointu** [comment]
I just check and when you use `VRouter.locale` it just passes this argument down to `MaterialApp.locale`so I don't see where there would be any issue. I would be very interested to see a small example of what does not work 🤔

**Comment by lulupointu** [comment]
I just dug up in the easy_localization package and found [this issue](https://github.com/aissat/easy_localization/issues/264) which looks very similar to yours.

**Comment by lulupointu** [comment]
This should be fixed now. I did try it myself no I am closing this. If you still have issues with easy_localization please reopen this

**Comment by Aerofluxx** [comment]
I can confirm this issue is resolved by the last update `vrouter: ^1.1.4+4`
