### ISSUE TITLE
VMaterialApp is gone?

### ISSUE THREAD

**Issue by Aerofluxx** [lulupointu/vrouter#62]
Hey,

with one of the updates between `vrouter: ^1.1.0+20` and `vrouter: ^1.1.2+4` the VMaterialApp is gone.

There are no "breaking changes" I can find to fix this problem. Maybe you could post a little breaking change for this? :)

Also - the discord link to your server is not valid anymore. Could you post a new one?

Thanks a ton! 💙

**Comment by lulupointu** [comment]
Hi,

thanks for opening this issue, this was a mistake, `VMaterialApp` is still here I just forgot to export it when refactoring.
Also the discord link should now be valid forever.
Just update to `>v1.1.2+5`

Thanks again !

**Comment by Aerofluxx** [comment]
Perfect, works great again with 1.1.2+5 - as always thank you so so much for this router, for my use case it's still perfect.
