### ISSUE TITLE
What is the `:_(.+)`  in path?

### ISSUE THREAD

**Issue by johnwangwjq** [lulupointu/vrouter#64]
I know regular expression. Only that I've not found any detailed documentation on how VRouter apply it. Especially what is the leading underscore in my example. I came across it in the [example code](https://vrouter.dev/guide/Examples/Path%20parameters) of the document. The comment on that code say `":_ designate a path parameter named \u0022_\u0022"`, yet I've no idea what that means. 

According to the example code `VRouteRedirector(path: ':_(.+)', redirectTo: '/user/bob')` followed the comment, if I understand right, when I type in an url like`/user/_anything`, the page should be changed to bob, but it didn't. It shows the page of "_anything". 

Could anybody show me any other doc on this topic? I'd like to know where my understanding goes wrong.

Thanks for the awsome package BTW.

**Comment by lulupointu** [comment]
Hey, here are some do'c about this: https://vrouter.dev/guide/Advanced/Path%20parameters/Advanced%20Pattern%20Matching

Tell me if it's not enough I'll explain it to you!

**Comment by johnwangwjq** [comment]
Thank you @lulupointu, that's good enough for me now. I just realized what's really not clear to me are those router concepts(eg., stacked, guard etc). I'll figure them out anyway.

**Comment by lulupointu** [comment]
I understand that this can be a lot to take in a at first. I suggest to have a look at vrouter.dev at first, this should be enough to get started!

**Comment by johnwangwjq** [comment]
Thanks alot for your kind response, and yes I guess I run too fast through vrouter.dev to really understand them all. ;-b

Anyway, and sorry for asking for extra help here, I'm rush in writing some code to practice and stucked by the following code(vrouter + provider):

What I'm trying to do are 1>setting up some global states(eg., user session, settings etc), 2> protect all url from anonymous access. The problem is I don't know how to get access the UserSession state in `beforeEnter` of the `VGuard` below, because provider need a context to access the `ChangeNotiferProvider` which cannot be found in the callback of `beforeEnter`.

```dart
void main() {
  runApp(MultiProvider(
    /// Here we setup global states.
    providers: [
      ChangeNotifierProvider(
        create: (_) => AppSettings(),
      ),
      ChangeNotifierProvider(
        create: (_) => UserSession(),
      ),
      ChangeNotifierProvider(
        create: (_) => ShoppingCart(),
      ),
    ],

    /// Here we configure all of our routes.
    child: VRouter(
      debugShowCheckedModeBanner: false,
      // initialRoute: '/',
      routes: [
        VGuard(
          beforeEnter: (redirect) async {
            // How could I intercepte all the route paths and check if user has logged in by the global UserSession state?
          },
          stackedRoutes: [],
        ),
        VWidget(
          path: '/',
          widget: SelectProductsPage(),
        ),
        VWidget(
          path: '/login',
          widget: LoginPage(),
        ),
        VWidget(
          path: '/cart',
          widget: ShoppingCartPage(),
        ),
      ],
    ),
  ));
}
```

**Comment by lulupointu** [comment]
Simply wrap VRouter in a Builder! 😊

**Comment by johnwangwjq** [comment]
Wow, yes, it's that simple! Thank you so much. And what a wonderful community!  

I actually end up with a wrapping `Selector`.  For other newcomers later reference please allow me paste my updated demo code segement here:
```
    /// Here we configure all of our routes.
    child: Selector<UserSession, String?>(
      selector: (ctx, userSession) => userSession.user,
      builder: (ctx, user, child) => VRouter(
        debugShowCheckedModeBanner: false,
        // initialRoute: '/',
        routes: [
          VGuard(
            beforeEnter: (redirect) async {
              if (user == null && redirect.to != '/login') {
                final Map<String, String> nextUrl = {};
                if (redirect.from != null) {
                  nextUrl['next'] = redirect.from!;
                }
                return redirect.push('/login', queryParameters: nextUrl);
              }
            },
            stackedRoutes: [
              VWidget(
                path: '/',
                widget: SelectProductsPage(),
              ),
              VWidget(
                path: '/login',
                widget: LoginPage(),
              ),
              VWidget(
                path: '/cart',
                widget: ShoppingCartPage(),
              ),
              VRouteRedirector(path: ':_(.+)', redirectTo: '/'),
            ],
          ),
        ],
      ),
    ),
```
