### ISSUE TITLE
Can we have RouteGuards?

### ISSUE THREAD

**Issue by evandrmb** [lulupointu/vrouter#66]
Hi, I'm building a Flutter Website in one of my company projects and got really interested in VRouter after a tt made by Luke Pighetti about this package, but I don't think you currently support RouteGuards and that's a really important feature to me. Are there any plans on including something like it?

**Comment by lulupointu** [comment]
`VGuard` are supported and very powerful in `VRouter`. 
Here is an example: https://vrouter.dev/guide/Examples/Redirection

The trick is to use the following `VRouteElement`: `VGuard`

**Comment by evandrmb** [comment]
That's exactly what I needed! Didn't saw it the first time I've looked into the docs.
