### ISSUE TITLE
Using VRouter with custom initial url leads to an error

### ISSUE THREAD

**Issue by sergeylappo** [lulupointu/vrouter#67]
Adding initial URL to `VRouterDelegate` causes  nullptr exception:
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
#0      new VRouterDelegate (package:vrouter/src/core/vrouter_delegate.dart:131:34)
#1      main (package:vrouter_example/main.dart:9:21)
#2      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
#3      _rootRun (dart:async/zone.dart:1428:13)
#4      _CustomZone.run (dart:async/zone.dart:1328:19)
#5      _runZoned (dart:async/zone.dart:1863:10)
#6      runZonedGuarded (dart:async/zone.dart:1851:12)
#7      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
```

To reproduce:

- For instance use `MaterialApp.router`
- Use Example
- Add initialUrl: '/login'

Modified main with the issue being reproducible:
https://gist.github.com/sergeylappo/9a080da84da95890b49af082804866b0

**Comment by lulupointu** [comment]
Thanks I will have a look, this should be simple to fix.

**Comment by lulupointu** [comment]
This should now be fixed in `v2.2.3`, could you confirm ?

**Comment by lulupointu** [comment]
This should be fixed. Could you confirm? (I did try with your shared code and it does seem to work).

Also thanks for the very clear issue, a pleasure :)

**Comment by sergeylappo** [comment]
@lulupointu seems to be working fine, thanks!
