### ISSUE TITLE
Support CupertinoApp / WidgetsApp

### ISSUE THREAD

**Issue by johnpryan** [lulupointu/vrouter#68]
Hi @lulupointu, I noticed that the `VRouter` class uses `MaterialApp.router`, which assumes that the user wants to build a Material Design app. Are there any plans to support CupertinoApp and WidgetsApp in the future?

**Comment by lulupointu** [comment]
You can use `VCupertinoApp` or `VWidgetApp`.
Even more flexible you can use `...App.router` with `VBackButtonDispatcher` and `VRouterDelegate`.in that case VRouter Delegate will contain the `routes`.

**Comment by johnpryan** [comment]
👍 That works great. Thanks!
