### ISSUE TITLE
Navigate without context, just by using a key

### ISSUE THREAD

**Issue by felixwortmann** [lulupointu/vrouter#7]
Is it possible to navigate without context, just by using a key?<br>
I am thinking about something like [this](https://medium.com/flutter-community/navigate-without-context-in-flutter-with-a-navigation-service-e6d76e880c1c).

**Comment by lulupointu** [comment]
You cannot as of yet but I will fix this by tomorrow and let you know how to.

**Comment by felixwortmann** [comment]
Thanks for the fast response and for building this great package.

**Comment by lulupointu** [comment]
Done.

Here is how you can achieve what you want:

1. Create a GlobalKey:

```dart
final vRouterKey = GlobalKey<VRouterState>();
```

2. Give the GlobalKey to `VRouter`

```dart
VRouter(
      key: vRouterKey,
      ...
)
```

3. Use it to navigate without context

```dart
vRouterKey.currentState.push('...')
```

**Comment by felixwortmann** [comment]
lgtm

**Comment by kevlar700** [comment]
Is there a recommended way of avoiding can't be unconditionally invoked because the receiver can be null for currentState?
