### ISSUE TITLE
[Question] VNester with BottomBarNavigation and stacked routes

### ISSUE THREAD

**Issue by jeprojects** [lulupointu/vrouter#70]
Thanks for building this package! I am wondering if you could help me a little.

`HomeScreen()` builds a page with the `BottomBarNavigation()` widget which works great for `FeedScreen()` and `SettingsScreen()` but for `SettingsDetail()` I would like it to not use the widgets from `HomeScreen()` and build the page using its own Scaffold etc. It will need to still be able to close SettingsDetail() page and return to the SettingsScreen().

```dart
VNester(
    path: '/',
    widgetBuilder: (child) => HomeScreen(child),
    nestedRoutes: [
        VWidget(path: null, widget: FeedScreen()),
        VWidget(path: '/settings', widget: SettingsScreen(),
            stackedRoutes: [
                VWidget(path: 'details', widget: SettingsDetail())
            ])
    ]
)
```

**Comment by lulupointu** [comment]
Hi, I made a tutorial about just this, [check it out](https://vrouter.dev/guide/Advanced/Custom%20VRouteElement%20And%20Scaling) and tell me if this does it for you !

**Comment by jeprojects** [comment]
Perfect thanks!
