### ISSUE TITLE
initial or beforeEnter in VRouter not effect

### ISSUE THREAD

**Issue by 86driver** [lulupointu/vrouter#71]
![image](https://user-images.githubusercontent.com/38236070/119863655-5f2aeb00-bf4c-11eb-86ec-ded030f8c176.png)

![image](https://user-images.githubusercontent.com/38236070/119863710-6eaa3400-bf4c-11eb-86e0-5c31be91acd7.png)

**Comment by lulupointu** [comment]
This is because you use `VMaterialApp` **on top** of `VRouter`.

You should:
    - Remove it and use `VRouter` as your top `MaterialApp`
    - If you need to use `VMaterialApp` at some point, use it bellow `VRouter` (but really you don't need it here)

**Comment by 86driver** [comment]
> This is because you use `VMaterialApp` **on top** of `VRouter`.
> 
> You should:
> - Remove it and use `VRouter` as your top `MaterialApp`
> - If you need to use `VMaterialApp` at some point, use it bellow `VRouter` (but really you don't need it here)

i dont know how to do,  could you show me a example code?

**Comment by lulupointu** [comment]
Just remove `VMaterialApp` :wink:

**Comment by lulupointu** [comment]
Tell me how it goes !

**Comment by 86driver** [comment]
> Let me know how it goes !

it too late...,   if i solved this question, i will tell you at once

**Comment by 86driver** [comment]
> Let me know how it goes !

okay, i solved this question from your help, thanks!

![image](https://user-images.githubusercontent.com/38236070/120220351-2e5df500-c26f-11eb-90dc-6cebfa4db105.png)

**Comment by 86driver** [comment]
but now i have another problem...

how history mode work...

below is my code :
![image](https://user-images.githubusercontent.com/38236070/120220710-c1972a80-c26f-11eb-9b0f-411ea00034b0.png)


problem:
![image](https://user-images.githubusercontent.com/38236070/120220758-d2e03700-c26f-11eb-86e7-346aadf8b304.png)

**Comment by lulupointu** [comment]
Are you sure you are on the latest version of `VRouter` ?

**Comment by 86driver** [comment]
> Are you sure you are on the latest version of `VRouter` (ie v `1.1.4+4`)?
> Try to `flutter clean` then `flutter pub get`
> I would be very surprised if you still have this issue. You are not using the `url_strategy` package are you ?

below is my code:
![image](https://user-images.githubusercontent.com/38236070/120272220-45d4c680-c2df-11eb-88c1-9ba65f4c0636.png)

and yaml:
![image](https://user-images.githubusercontent.com/38236070/120272251-538a4c00-c2df-11eb-9aa8-edb8f76654b9.png)

it  says cannot set yr strategy more than once.

if i update vrouter to vrouter: ^1.1.4+4, command told me must update environment sdk to ">=2.13.0 <3.0.0".

so ,  if i want historymode works in vrouter, i must update environment sdk to ">=2.13.0 <3.0.0" ?

**Comment by lulupointu** [comment]
It would be the best thing to do.
Is there anything preventing you to update your sdk constraints?

**Comment by 86driver** [comment]
> It would be the best thing to do.
> Is there anything preventing you to update your sdk constraints?

it still not work when i update environment sdk, how should i do

**Comment by lulupointu** [comment]
Did you:
1. Update sdk constraints
2. Update VRouter to last version (`1.1.4+4`)
3. Run `flutter clean`
4. Run `flutter pub get`

?

**Comment by 86driver** [comment]
> Did you:
> 
> 1. Update sdk constraints
> 2. Update VRouter to last version (`1.1.4+4`)
> 3. Run `flutter clean`
> 4. Run `flutter pub get`
> 
> ?

yes, i am sure.... or it not work in dev mode?

**Comment by 86driver** [comment]
> > Did you:
> > 
> > 1. Update sdk constraints
> > 2. Update VRouter to last version (`1.1.4+4`)
> > 3. Run `flutter clean`
> > 4. Run `flutter pub get`
> > 
> > ?
> 
> yes, i am sure.... or it not work in dev mode?

sorry , it works after i updated and  remove url_strategy in my project. thanks!

**Comment by lulupointu** [comment]
Oh god I missing one of your screenshot sorry for wasting your time!

You should remove `setPathUrlStrategy`, and your dependency on `url_strategy` entirely. `VRouter` does this for you, no need to handle it manually.

Sorry again

**Comment by lulupointu** [comment]
Well at the same time. Glad it's solved :wink: !
