### ISSUE TITLE
Add debug Logs

### ISSUE THREAD

**Issue by evandrmb** [lulupointu/vrouter#73]
I believe that adding some debug logs to the package would help a lot. As shown in Discord yesterday, some users (aka me) may have a bit of difficulty adapting to the Navigator, leading them to make simple mistakes. That said if the package prints in debugging the route that's being pushed would help a lot.

Example:
Today I was pushing a route and instead of the expected result my redirector was leading to the unknown route, after I put some Guard in the redirector to print the route I was pushing, I realized that instead of `/v1/ctg/30` I was pushing `v1/ctg/41/ctg/30` because I was already in `ctg/41`.

**Comment by evandrmb** [comment]
You may argue that the users could do the same thing I did and add a `VGuard` in redirector to print the wrong calls, but I believe that the package naturally giving logs would be more productive.

**Comment by lulupointu** [comment]
Fair enough, I'll see what I can do

**Comment by evandrmb** [comment]
It just occurred to me that some devs may not like that kind of log, so it would be a good UX decision to have a flag that disables it. Just like `Logger.root.level = Level.OFF;` from the logging package

**Comment by lulupointu** [comment]
Yes of course, as an attribute of `VRouter` (just like `debeugBanner...` for `MaterialApp`.

**Comment by evandrmb** [comment]
That's perfect!

**Comment by Techno-Disaster** [comment]
This would be super helpful to have :), Currently have to develop on web to check url, which can be a bit bothersome

**Comment by lulupointu** [comment]
This will (finally) be brought to `v1.2`. I'm updating the documentation for this and everything but this should be out in a few days

**Comment by evandrmb** [comment]
Excited to test it!

**Comment by lulupointu** [comment]
`v1.2` is out, and logs are baked in ! 

I did only make messages to print for navigation event but the system is expendable and could include other hint/warning if need be. 
Feel free to tell me what you think and pop in discord for any suggestion on what to add if any !
