### ISSUE TITLE
Would be nice if we could use `CupertinoApp.router`

### ISSUE THREAD

**Issue by esDotDev** [lulupointu/vrouter#79]
Is there any way to use CupertinoApp.router instead of MaterialApp.router?

**Comment by lulupointu** [comment]
simple use `VCupertinoRouter` :wink:

**Comment by esDotDev** [comment]
This is not showing up for me in 1.1.1+4

**Comment by lulupointu** [comment]
Upgrade to `1.1.4+4` then :wink:

**Comment by esDotDev** [comment]
Woops, that's what I mean, can't see it?
![image](https://user-images.githubusercontent.com/736973/120374650-0dc98580-c2d7-11eb-87a8-93ad820dbf70.png)

Cant see it here either: https://github.com/lulupointu/vrouter/search?q=VCupertino

**Comment by lulupointu** [comment]
Oh sorry it is `CupertinoVRouter` 🤦‍♂️
