### ISSUE TITLE
Rename Error Messages

### ISSUE THREAD

**Issue by evandrmb** [lulupointu/vrouter#80]
I've got a `The url '/' has no matching route.
Consider using VRoute(path: '.*', widget: UnknownPathWidget()) at the bottom of your VRouter routes to catch any wrong route.` and was wondering if instead of `VRouter` shouldn't we have `VWidget`?

**Comment by evandrmb** [comment]
If so I would be happy to make a contribution. :)

**Comment by lulupointu** [comment]
Oh you are right, how did I not see that x)

you can make a contribution sure! I'll wait for it this time :smile:

**Comment by evandrmb** [comment]
Should I target main or dev?

**Comment by lulupointu** [comment]
You did well, thanks again! 😊
