### ISSUE TITLE
Would be nice to have .navigatorKey on `VRouter` 

### ISSUE THREAD

**Issue by esDotDev** [lulupointu/vrouter#82]
It seems we need to use VNester in order to pass a nav key to the VRouter, is this the case? If so, would be nice to be able to pass it to the top level VRouter element. 

Additionally, there seems to be some delay before the Navigator is created. I would like to use the key to gain access to a context that can be used to showDialogs globally. Something like:

```
final GlobalKey<NavigatorState> _navigatorKey = GlobalKey();
initState(){
  scheduleMicroTrack(() => print(_navigatorKey.context))
}

build => VRouter(routes: [
            VNester(
              path: null,
              navigatorKey: _navigatorKey,
              nestedRoutes: [VWidget(path: ViewRoutes.Splash.path, widget: SplashView())],
              widgetBuilder: (c) => c,
            ),)
```
Is there another better way to get a context that is below the Navigator/Overlay?

**Comment by esDotDev** [comment]
Essentially I want to be able to call `showDialog()` from any of my views, without having to actually pass `context` along for the ride.

I'm having trouble actually getting that context when using VRouter. Passing in a key to VNester seems to work, but is easily broken, as not all routes are inside my Nester (for example, `SplashPage` is not nested by the shared app scaffold)

If the first route shown is not inside a Nester, it seems the nav key is not assigned, and I get a runtime exception.

**Comment by lulupointu** [comment]
Several things:
1. Not being able set the root navigation key is a mistake. I did have this option before and must have missed it during some refactoring
2. Using showX is a bit of an anti pattern is not recommanded (even if it's fully supported), see [this comment and discussion](https://github.com/lulupointu/vrouter/issues/63#issuecomment-844838998) if you are interested

I will fix point 1 though, I'll update you here!

**Comment by esDotDev** [comment]
Thx! Not sure I would call it an anti-pattern
* I don't actually want most of my dialogs to be associated with a route name
* Most users in web don't expet that Backbtn closes dialogs
* It's more boilerplate, especially when doing common things like OkCancel dialogs that have a response, nicer to just roll with the devil we know here.

It's certainly a cool pattern though and we'll keep it in mind!

**Comment by lulupointu** [comment]
`navigatorKey` can now be specified in as of `1.1.4+7`.

You are right, anti-pattern is not the right word, there are definitely valid cases! From my point of view I think a `Dialog` is ok, but a huge `BottomSheet` containing information should be part of the path.

Feel free to close if `navigatorKey` works as intended after your tests !

**Comment by benz93chung** [comment]
Thanks @esDotDev for the issue and @lulupointu for looking into adding ```navigatorKey``` for I was also intending to ```showDialog``` globally.

However, according to my experience, the ```navigatorKey``` does not seem to work to my intentions with it. At where the navigator key was being accessed for showing a dialog, the ```currentState``` and ```currentContext``` turned out to be null.

Any advice to this? Any response would be appreciated.

Just for your information, here below are the widgets, keys and the VRouter configuration that were used in my testing:

#### widget_keys.dart
```dart
class WidgetKeys {
  static final navKey = GlobalKey<NavigatorState>();
}
```

#### main.dart
```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      debugShowCheckedModeBanner: false,
      navigatorKey: WidgetKeys.navKey,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      routes: [
        VWidget(
          path: '/home',
          widget: MyHomePage(),
        ),
        VWidget(
          path: '/anotherPage',
          name: 'anotherPage',
          widget: AnotherPage(),
        ),
        VRouteRedirector(
          path: ':_(.*)',
          redirectTo: '/home',
        ),
      ],
    );
  }
}
```

#### home_page.dart
```dart
class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home Page'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextButton(
              child: Text('Next page!'),
              onPressed: () {
                context.vRouter.pushNamed('anotherPage');
              },
            ),
          ],
        ),
      ),
      floatingActionButton: ShowDialogFab(),
    );
  }
}
```

#### another_page.dart
```dart
class AnotherPage extends StatelessWidget {
  const AnotherPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Another Page'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextButton(
              child: Text('Go home!'),
              onPressed: () {
                context.vRouter.push('/home');
              },
            ),
          ],
        ),
      ),
      floatingActionButton: ShowDialogFab(),
    );
  }
}
```

#### show_dialog_fab.dart
```dart
class ShowDialogFab extends StatelessWidget {
  const ShowDialogFab({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return FloatingActionButton(
      onPressed: () {
        final navKeyContext = WidgetKeys.navKey.currentState!.overlay!.context;

        showDialog(
          context: navKeyContext,
          builder: (context) => AlertDialog(
            title: Text('I am a dialog'),
            content: Text('Triggered with NavKey context'),
            actions: <Widget>[
              TextButton(
                child: Text(
                  'OK',
                ),
                onPressed: () => Navigator.of(context).pop(),
              ),
            ],
          ),
        );
      },
      tooltip: 'Trigger alert dialog',
      child: Icon(Icons.notifications),
    );
  }
}
```

**Comment by lulupointu** [comment]
That's because I'm stupid 🤦

Anyway that's fixed in `1.1.4+9`

Also you can just use `WidgetKeys.navKey.currentContext!` no need to go after the overlay.

**Comment by benz93chung** [comment]
That's fast!
Alright, I can confirm that using ```showDialog``` globally with navigator key works!

Big up to you, overall I really like this library! @esDotDev please confirm if it worked for you too 😄

**Comment by esDotDev** [comment]
Works great, ty!
