### ISSUE TITLE
Could not find VRouterScope above this Builder Widget. when i use vRouter with Getx

### ISSUE THREAD

**Issue by WangMiaoGit** [lulupointu/vrouter#87]
final vRouterDelegate = VRouterDelegate(
      routes: GetRouter.getRoutes(),
    );

  return GetMaterialApp.router(
      routeInformationParser: VRouteInformationParser(),
      routerDelegate: vRouterDelegate,
      // Here is the equivalent to VRouter.routes
      backButtonDispatcher: VBackButtonDispatcher(),
    );

**Comment by lulupointu** [comment]
You must put `VRouterScope` at the top of your widget tree, as mentioned in the error message :wink:

**Comment by WangMiaoGit** [comment]
But before today, no such error was reported.

**Comment by WangMiaoGit** [comment]
When I use GetX with VRouter, the root widget is GetMaterialApp

**Comment by lulupointu** [comment]
> But before today, no such error was reported.

You must have updated `VRouter`

> When I use GetX with VRouter, the root widget is GetMaterialApp

 Wrap `GetMaterialApp` in VRouterScope like so:

```dart
VRouterScope(
  child: GetMaterialApp(...)
)
```

**Comment by WangMiaoGit** [comment]
Thank you for your answer. Problem solved.
