### ISSUE TITLE
Get relative path

### ISSUE THREAD

**Issue by lulupointu** [lulupointu/vrouter#88]
Hi @lulupointu, Thanks for the quick update but it's giving the relative path not the pathname. For example:

```dart
VNester(
  path: "/integrations/mysqlDB", 
  widgetBuilder: (child) => EmptyBaseScreen(child), 
  nestedRoutes: [
    VWidget(name: "allMySqlDBIntegrations", path: null, widget: MySqlIntegrationScreen()),
    VWidget(name: "mysqlDBSettings", path: "settings", widget: new MySqlSettingsScreen()),
  ],
),
```

when i am on the "MySqlIntegrationScreen" screen, i wanted to get "allMySqlDBIntegrations" as the pathname and not "/integrations/mysqlDB" .

This is useful when I want to check the current route of the app. Because in the case of dynamic path params, it is difficult to understand the current route from a dynamic path. If I get the name of the route, it becomes much simpler to figure out the actual route. Let me know if you need any elaborated examples.

_Originally posted by @rohitranjan1991 in https://github.com/lulupointu/vrouter/issues/8#issuecomment-852977221_

**Comment by lulupointu** [comment]
@rohitranjan1991 I am not sure I see where this would be usefull.

If you need to access `pathParameters` why not just use `context.vRouter.pathParameters` ? This is way easier than parsing the url by hand !

Using the same logic, you can even use path parameters + regexp to get what you want here (though I don't really userstand why):
```dart
VNester(
  path: "/integrations/mysqlDB", 
  widgetBuilder: (child) => EmptyBaseScreen(child), 
  nestedRoutes: [
    VWidget(name: ":localPathName(allMySqlDBIntegrations)", path: null, widget: MySqlIntegrationScreen()),
    VWidget(name: ":localPathName(mysqlDBSettings)", path: "settings", widget: new MySqlSettingsScreen()),
  ],
),
```

You can then use `context.vRouter.pathParameters['localPathName']` to access the information you where looking for in your original question.

**Comment by rohitranjan1991** [comment]
Hi @lulupointu , I don't need access to the path params actually. From within a widget, I need to check, under which path was this widget loaded. So in this case, currently I have to compare the URL to check under which path/URL was this widget loaded onto. This works fine if I have a static path for e.g. /a/b/c but I can't compare the full URL in case of a dynamic URL for eg. /a/:param1/c, because the value of "param1" can be anything.

VNester(
  path: "/integrations/mysqlDB", 
  widgetBuilder: (child) => EmptyBaseScreen(child), 
  nestedRoutes: [
    VWidget(name: "settings", path: "/:kiid/settings", widget: new MySqlSettingsScreen()),
    VWidget(name: "instructions", path: "/instructions/:kiid/settings", widget: new MySqlSettingsScreen()),
  ],
),

Now in this scenario, the "MySqlSettingsScreen" is loaded from two paths, and I need to know if this screen was loaded as a "settings" or "instructions". For this purpose, if I get the name of the widget from above (in this case "settings" and "instructions"), it would be a very simple comparison for me. I hope, I am able to explain this time better than last time. :-)

**Comment by lulupointu** [comment]
I see, why not use `context.vRouter.path.contains('instructions')` then ?

I understand what you want but I think this works great. In any case 1 `routeStack` = 1 url so `contains` should be applicable in most situations.

In any case I think you should approach this like so:

```dart
VNester(
  path: "/integrations/mysqlDB", 
  widgetBuilder: (child) => EmptyBaseScreen(child), 
  nestedRoutes: [
    VWidget(name: "settings", path: "/:kiid/settings", widget: new MySqlSettingsScreen(isInstructions: false)),
    VWidget(name: "instructions", path: "/instructions/:kiid/settings", widget: new MySqlSettingsScreen(isInstructions: true)),
  ],
),
```

**Comment by rohitranjan1991** [comment]
There are other cases where just string comparison would become messy for me given the complex routes I have to support. maybe I can explain over a call :-) . Also, is it a lot of work to provide the name of the route?

**Comment by lulupointu** [comment]
What you mean be name is the "raw" name ? 

Like `/:kiid/settings` instead of `whatever/settings`?

We can have a call if you want, join the discord channel we'll go to the voice channel

**Comment by lulupointu** [comment]
I'll close this since we talked it through.

For reference, this is basically what was suggested:
```dart
VNester(
  path: "/integrations/mysqlDB", 
  widgetBuilder: (child) => EmptyBaseScreen(child), 
  nestedRoutes: [
    VWidget(name: "settings", path: "/:kiid/settings", widget: new MySqlSettingsScreen(name: "settings")),
    VWidget(name: "instructions", path: "/instructions/:kiid/settings", widget: new MySqlSettingsScreen(name: "instructions")),
  ],
),
```

To make this more flexible, we also proposed to pass the name into a provider to be able to access it anywhere.
