### ISSUE TITLE
Switch (fast) multiple times between tabs, throws. 

### ISSUE THREAD

**Issue by kebj** [lulupointu/vrouter#91]
When I switch (fast) multiple times between tabs. this code throws. Mybe its some underlaying problem in navigator.dart ?
See:
"Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md"
 

Code:
```
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(
    VRouter(
      debugShowCheckedModeBanner: false,
      routes: [
        VNester(
          path: '/',
          widgetBuilder: (child) => MyScaffold(child), // Child is the widget from nestedRoutes
          nestedRoutes: [
            VWidget(path: null, widget: HomeScreen()), // null path matches parent
            VWidget(path: 'settings', widget: SettingsScreen()),
          ],
        ),
      ],
    ),
  );
}

abstract class BaseWidget extends StatelessWidget {
  String get title;

  String get buttonText;

  String get pushTo;

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(title),
            SizedBox(height: 50),
            ElevatedButton(
              onPressed: () => context.vRouter.push(pushTo),
              child: Text(buttonText),
            ),
          ],
        ),
      ),
    );
  }
}

class MyScaffold extends StatelessWidget {
  final Widget child;

  const MyScaffold(this.child);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: child,
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: context.vRouter.url!.contains('settings') ? 1 : 0,
        onTap: (value) => context.vRouter.push((value == 0) ? '/' : '/settings'),
        items: [
          BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
          BottomNavigationBarItem(icon: Icon(Icons.settings), label: 'Settings'),
        ],
      ),
    );
  }
}

class HomeScreen extends BaseWidget {
  @override
  String get title => 'Home';

  @override
  String get buttonText => 'Go to Settings';

  @override
  String get pushTo => '/settings';
}

class SettingsScreen extends BaseWidget {
  @override
  String get title => 'Settings';

  @override
  String get buttonText => 'Go to Home';

  @override
  String get pushTo => '/';
}
```

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Builder:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3784 pos 14: '!pageKeyToOldEntry.containsKey(page.key)': is not true.
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
Scaffold
lib\main.dart:56
When the exception was thrown, this was the stack
#2      NavigatorState._updatePages
package:flutter/…/widgets/navigator.dart:3784
#3      NavigatorState.didUpdateWidget
package:flutter/…/widgets/navigator.dart:3606
#4      StatefulElement.update
package:flutter/…/widgets/framework.dart:4761
#5      Element.updateChild
package:flutter/…/widgets/framework.dart:3350
#6      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4599
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Each child must be laid out exactly once.
The relevant error-causing widget was
Scaffold
lib\main.dart:56

**Comment by lulupointu** [comment]
Please check this https://github.com/lulupointu/vrouter/issues/77 😊

**Comment by kebj** [comment]
Thanks! 👍
