### ISSUE TITLE
how can i use in path parameters a "/" symbol 

### ISSUE THREAD

**Issue by basketball-ico** [lulupointu/vrouter#98]
I want to have a page in which if there is no route define, like a `HomePage` in my example, I can pass that route as a parameter, in my example to `PostPage`, since I want to keep that url.
with the id I usually fetch a file that has the same/similar url in my backend, but I don't want to define a path explicitly since there are many.

```dart
    www.app.com/i/am/a/path/param
```

 ```dart
 VWidget(
  path: '/',
    widget: HomePage(),
),
 VWidget(
  path: '/:id',
    widget: PostPage(),
),
```

**Comment by lulupointu** [comment]
```dart
VWidget(
 path: '/',
   widget: HomePage(),
),
VWidget(
 path: '/:id(.*)'',
   widget: PostPage(),
),
```

Would this work ? Here id *can* contain "/" since you allow any symbol with the regexp .*

**Comment by basketball-ico** [comment]
works great, thanks
